export type QuestCategory =
  | "Chaos"
  | "Outdoor"
  | "Social"
  | "Creative"
  | "Food"
  | "Late Night"
  | "Chill"
  | "Fitness"
  | "Nature"
  | "Tech"
  | "Exploration"
  | "Indoor";

export type QuestCost = "free" | "$" | "$$" | "$$$";

export type QuestTemplate = {
  id: string;
  title: string;
  description: string;
  category: QuestCategory;
  spice: number; // 1-10
  minGroup: number;
  maxGroup: number;
  minTime: number; // minutes
  maxTime: number;
  cost?: QuestCost;
  lateNight?: boolean;
  // OSM tag values to look for if we have nearby-place data. If a match is
  // found, {venue} in title/description is replaced with the real venue name.
  venueQuery?: string[];
};

// {city} and {venue} are substituted at generation time.
export const QUESTS: QuestTemplate[] = [
  // ===== Chaos =====
  { id: "rps-stranger", title: "Stranger Rock Paper Scissors", description: "Step outside in {city}. Challenge 5 strangers to rock paper scissors. Winner picks where the group goes next.", category: "Chaos", spice: 6, minGroup: 1, maxGroup: 4, minTime: 30, maxTime: 60, cost: "free" },
  { id: "high-five-50", title: "50 High-Fives", description: "Get 50 high-fives from strangers in {city} within 60 minutes. Split the count across the group.", category: "Chaos", spice: 7, minGroup: 2, maxGroup: 8, minTime: 60, maxTime: 90, cost: "free" },
  { id: "elevator-song", title: "Elevator Song", description: "Find a public elevator in {city}. Sing one full chorus of a song before you reach your floor.", category: "Chaos", spice: 9, minGroup: 2, maxGroup: 4, minTime: 15, maxTime: 30, cost: "free" },
  { id: "compliment-loud", title: "Loud Compliment Loop", description: "In a public square in {city}, deliver a loud, specific compliment to 3 different strangers each.", category: "Chaos", spice: 8, minGroup: 2, maxGroup: 6, minTime: 30, maxTime: 60, cost: "free" },
  { id: "free-fortune", title: "Sidewalk Fortune Teller", description: "Set up as a free fortune teller in a busy spot in {city}. Get 5 willing strangers to sit for a reading within 60 minutes.", category: "Chaos", spice: 8, minGroup: 3, maxGroup: 6, minTime: 60, maxTime: 120, cost: "free" },
  { id: "swap-shoes", title: "Swap Shoes for 20 Minutes", description: "Pair up. Swap one shoe each. Walk 20 minutes around {city} on mismatched feet.", category: "Chaos", spice: 6, minGroup: 2, maxGroup: 6, minTime: 20, maxTime: 45, cost: "free" },
  { id: "balloon-deliver", title: "Random Balloon Delivery", description: "Buy a single balloon in {city}. Gift it to a stranger with a quick compliment. Snap a photo of the moment if they're up for it.", category: "Chaos", spice: 7, minGroup: 2, maxGroup: 4, minTime: 45, maxTime: 90, cost: "$" },
  { id: "fake-names", title: "Fake Names Mission", description: "Pick a fake name each. For the next 60 minutes in {city}, use that name at every order, intro, and checkout.", category: "Chaos", spice: 6, minGroup: 2, maxGroup: 6, minTime: 60, maxTime: 90, cost: "$" },
  { id: "synchronized-walk", title: "Synchronized Walk", description: "Walk through {city} in perfect lockstep for 5 minutes straight. Photograph yourselves doing it at 3 different spots.", category: "Chaos", spice: 5, minGroup: 3, maxGroup: 6, minTime: 30, maxTime: 60, cost: "free" },
  { id: "tiny-parade", title: "Tiny Parade", description: "Pick a theme. March in formation for 10 minutes through {city}. Take a group photo at the end.", category: "Chaos", spice: 8, minGroup: 3, maxGroup: 10, minTime: 30, maxTime: 60, cost: "free" },
  { id: "bus-roulette", title: "Bus Roulette", description: "Board the next bus or train leaving {city}'s nearest stop. Ride 4 stops. Get off. Find food within 10 minutes.", category: "Chaos", spice: 6, minGroup: 1, maxGroup: 8, minTime: 60, maxTime: 180, cost: "$$" },
  { id: "fortune-cookie-mission", title: "Fortune Cookie Mission", description: "Find a fortune cookie in {city}. Whatever it says, the group does it (within reason) inside the hour.", category: "Chaos", spice: 7, minGroup: 2, maxGroup: 6, minTime: 60, maxTime: 120, cost: "$" },
  { id: "uber-roulette", title: "Rideshare Roulette", description: "Open a rideshare app in {city}. Pick the third suggestion. Go there. Find dinner within 15 minutes of arrival.", category: "Chaos", spice: 6, minGroup: 2, maxGroup: 4, minTime: 90, maxTime: 180, cost: "$$" },
  { id: "dance-floor-import", title: "Dance Floor Import", description: "Find a place in {city} with music. Start a 30-second dance routine. See how many strangers join in.", category: "Chaos", spice: 7, minGroup: 3, maxGroup: 8, minTime: 30, maxTime: 90, cost: "$", lateNight: true },
  { id: "open-mic-dare", title: "Open Mic Dare", description: "Find an open mic tonight in {city}. One member of the group performs. The audience picks the topic on the spot.", category: "Chaos", spice: 9, minGroup: 2, maxGroup: 6, minTime: 90, maxTime: 180, cost: "$", lateNight: true },
  { id: "weirdest-cart", title: "1am Weirdest-Cart Audit", description: "Hit {venue} in {city} (or any 24-hour store). Fill one shared cart with the weirdest items under $3 each. Pay together at checkout.", category: "Late Night", spice: 7, minGroup: 2, maxGroup: 6, minTime: 45, maxTime: 90, cost: "$$", lateNight: true, venueQuery: ["supermarket"] },
  { id: "yes-day-mini", title: "Mini Yes-Day", description: "For the next 90 minutes in {city}, say yes to any reasonable suggestion from any group member.", category: "Chaos", spice: 8, minGroup: 2, maxGroup: 6, minTime: 90, maxTime: 180, cost: "$$" },

  // ===== Outdoor =====
  { id: "skyline-hunt", title: "Skyline Hunt", description: "Head to {venue} in {city} (or the highest publicly accessible vantage point you can find). Take a group photo at the top.", category: "Outdoor", spice: 4, minGroup: 1, maxGroup: 8, minTime: 60, maxTime: 120, cost: "free", venueQuery: ["viewpoint", "attraction"] },
  { id: "playground-takeover", title: "Playground Takeover", description: "Meet at {venue} in {city}. Hold a 10-minute swing competition. Loser buys snacks.", category: "Outdoor", spice: 3, minGroup: 2, maxGroup: 6, minTime: 30, maxTime: 60, cost: "free", venueQuery: ["playground"] },
  { id: "scavenger-five", title: "Five-Thing Scavenger", description: "In 60 minutes around {city}: find a feather, something purple, a free sticker, a stranger's recommendation, and a coin.", category: "Outdoor", spice: 3, minGroup: 2, maxGroup: 8, minTime: 60, maxTime: 75, cost: "free" },
  { id: "graffiti-tour", title: "Graffiti Self-Tour", description: "Walk a single mile in {city} photographing every piece of street art you spot. Vote on the best at the end.", category: "Outdoor", spice: 2, minGroup: 1, maxGroup: 6, minTime: 45, maxTime: 90, cost: "free" },
  { id: "skate-or-roll", title: "Skate or Roll", description: "Rent skates, scooters, or bikes in {city}. Pick a destination 2 miles away. Race there. Loser buys coffee for the group.", category: "Outdoor", spice: 5, minGroup: 2, maxGroup: 6, minTime: 60, maxTime: 120, cost: "$$" },
  { id: "alphabet-walk", title: "Alphabet Walk", description: "Walk through {city} and photograph 26 things, one per letter, in order. 90-minute time limit.", category: "Outdoor", spice: 4, minGroup: 1, maxGroup: 6, minTime: 90, maxTime: 120, cost: "free" },
  { id: "puddle-jump", title: "Puddle Jump Bracket", description: "After rain in {city}, find 5 puddles. Each person jumps each one. Group votes on the best splash photo.", category: "Outdoor", spice: 4, minGroup: 2, maxGroup: 6, minTime: 30, maxTime: 60, cost: "free" },
  { id: "snow-tag", title: "First Snow Tag", description: "If there's snow in {city}, play 10 minutes of tag. Loser flops down for a snow angel.", category: "Outdoor", spice: 5, minGroup: 3, maxGroup: 8, minTime: 30, maxTime: 60, cost: "free" },
  { id: "outdoor-photoshoot", title: "Outdoor Photoshoot", description: "Pick a magazine cover style. Recreate it outdoors in {city} with phone cameras. Best edit wins the round.", category: "Outdoor", spice: 5, minGroup: 2, maxGroup: 6, minTime: 60, maxTime: 120, cost: "free" },
  { id: "kite-fly", title: "Kite or Frisbee Session", description: "Buy or bring a kite or frisbee. Head to {venue} in {city}. Lose track of time for 60 minutes.", category: "Outdoor", spice: 3, minGroup: 2, maxGroup: 8, minTime: 60, maxTime: 90, cost: "$", venueQuery: ["park"] },
  { id: "free-paper", title: "Free-Newspaper Crawl", description: "Collect one free publication from 5 different spots in {city}. Read the weirdest line aloud at the end.", category: "Outdoor", spice: 3, minGroup: 1, maxGroup: 4, minTime: 60, maxTime: 90, cost: "free" },
  { id: "shadow-race", title: "Shadow Race", description: "On a sunny day in {city}, race to a chosen landmark stepping only on shadows. First to arrive wins.", category: "Outdoor", spice: 4, minGroup: 2, maxGroup: 6, minTime: 30, maxTime: 60, cost: "free" },
  { id: "open-air-market", title: "Open-Air Market Hunt", description: "Find an outdoor market in {city}. Each person buys the strangest $5 thing they can. Compare hauls on a bench.", category: "Outdoor", spice: 4, minGroup: 2, maxGroup: 6, minTime: 90, maxTime: 120, cost: "$$" },
  { id: "outdoor-trivia", title: "Outdoor Trivia Walk", description: "Walk through {city}. Pick 10 landmarks you see. Group quizzes each other about them on the spot using phones.", category: "Outdoor", spice: 3, minGroup: 2, maxGroup: 6, minTime: 60, maxTime: 90, cost: "free" },
  { id: "city-hike", title: "Urban Hike 5 Miles", description: "Walk 5 miles through {city} on streets you haven't taken before. Track the route on a map app.", category: "Outdoor", spice: 5, minGroup: 1, maxGroup: 6, minTime: 120, maxTime: 240, cost: "free" },
  { id: "stargaze-roof", title: "Rooftop Stargaze", description: "Find a publicly accessible rooftop or hill in {city}. Stay until you spot 10 stars. Make a wish each.", category: "Outdoor", spice: 4, minGroup: 2, maxGroup: 6, minTime: 60, maxTime: 120, cost: "free", lateNight: true },
  { id: "morning-coffee-walk", title: "Walking Coffee", description: "Buy coffee at {venue} in {city}. Walk and sip for 30 minutes wherever the streets take you.", category: "Outdoor", spice: 1, minGroup: 1, maxGroup: 6, minTime: 30, maxTime: 45, cost: "$", venueQuery: ["cafe"] },
  { id: "park-biggest-tree", title: "Biggest Tree in the Park", description: "Walk to the closest park in {city}. Find the biggest tree. Take a group photo with it. Identify the species with a plant ID app.", category: "Outdoor", spice: 2, minGroup: 1, maxGroup: 8, minTime: 30, maxTime: 60, cost: "free", venueQuery: ["park"] },
  { id: "water-rock-skip", title: "Find Water, Throw Something", description: "Go to the nearest body of water in {city} — fountain, pond, creek, lake. Skip a rock or throw a stick in.", category: "Outdoor", spice: 2, minGroup: 1, maxGroup: 8, minTime: 30, maxTime: 60, cost: "free" },
  { id: "fountain-wish", title: "Fountain Wish", description: "Walk to the nearest public fountain in {city}. Throw a coin in and make a wish out loud.", category: "Outdoor", spice: 1, minGroup: 1, maxGroup: 6, minTime: 20, maxTime: 45, cost: "$" },
  { id: "intersection-cars", title: "Intersection Car Colors", description: "Find a busy intersection in {city}. Count how many distinct car colors pass in 3 minutes. Compare guesses afterward.", category: "Outdoor", spice: 2, minGroup: 1, maxGroup: 6, minTime: 15, maxTime: 30, cost: "free" },
  { id: "outdoor-people-watch", title: "Outdoor Seating People-Watch", description: "Find the nearest place in {city} with outdoor seating. Order something small. People-watch for 15 minutes.", category: "Outdoor", spice: 2, minGroup: 1, maxGroup: 6, minTime: 30, maxTime: 60, cost: "$", venueQuery: ["cafe", "restaurant"] },
  { id: "park-stranger-game", title: "Park Game Challenge", description: "Walk to the closest park in {city}. Challenge a stranger to whatever's happening — frisbee, chess, basketball, anything.", category: "Outdoor", spice: 6, minGroup: 2, maxGroup: 6, minTime: 45, maxTime: 90, cost: "free", venueQuery: ["park"] },
  { id: "best-bench", title: "Best Bench Hunt", description: "Find and rate 5 benches in {city} by view, comfort, and vibes. Award a sticky note to the winner.", category: "Outdoor", spice: 1, minGroup: 1, maxGroup: 6, minTime: 60, maxTime: 120, cost: "free", venueQuery: ["park"] },
  { id: "rock-skip", title: "Rock-Skipping Tournament", description: "Find any body of water in {city} with rocks. Each person gets 10 attempts. Most skips wins.", category: "Outdoor", spice: 2, minGroup: 2, maxGroup: 6, minTime: 30, maxTime: 60, cost: "free" },

  // ===== Social =====
  { id: "stranger-compliments", title: "Stranger Compliment Chain", description: "Each person gives a genuine compliment to 5 strangers in {city}. Bonus point: get one to compliment you back.", category: "Social", spice: 4, minGroup: 2, maxGroup: 10, minTime: 30, maxTime: 90, cost: "free" },
  { id: "tech-meetup-chaos", title: "Tech Meetup Chaos Questions", description: "Crash a real startup or tech meetup in {city}. Each person gets a founder to answer one absurd question seriously.", category: "Social", spice: 5, minGroup: 2, maxGroup: 5, minTime: 60, maxTime: 150, cost: "free" },
  { id: "park-bench-philosophers", title: "Park Bench Philosophers", description: "Head to {venue} in {city}. Sit on different benches. Start 3-minute philosophy conversations with anyone nearby.", category: "Social", spice: 3, minGroup: 2, maxGroup: 6, minTime: 45, maxTime: 90, cost: "free", venueQuery: ["park"] },
  { id: "local-recs", title: "Local Recs Walk", description: "Ask 3 locals in {city} for their favorite hidden spot. Visit the top recommendation as a group.", category: "Social", spice: 4, minGroup: 2, maxGroup: 5, minTime: 90, maxTime: 180, cost: "$" },
  { id: "dollar-store-gifts", title: "Dollar Store Gift Exchange", description: "Everyone gets $5 at a dollar store in {city}. Buy gifts blindly for each other. Reveal at the nearest coffee shop.", category: "Social", spice: 3, minGroup: 3, maxGroup: 8, minTime: 45, maxTime: 75, cost: "$" },
  { id: "stranger-life-story", title: "Stranger Life Story", description: "Approach one stranger in {city}. Ask their life story. Buy them a coffee.", category: "Social", spice: 5, minGroup: 1, maxGroup: 4, minTime: 30, maxTime: 60, cost: "$" },
  { id: "thrift-outfit", title: "Thrift Outfit Swap", description: "$10 each at a thrift store in {city}. Pick out a full outfit for the person on your left. They wear it the rest of the day.", category: "Social", spice: 5, minGroup: 3, maxGroup: 8, minTime: 75, maxTime: 120, cost: "$$" },
  { id: "two-truths-locals", title: "Two Truths and a Local", description: "Each person collects one weird local fact from a stranger in {city}. Use them in a round of two truths and a lie later.", category: "Social", spice: 4, minGroup: 3, maxGroup: 6, minTime: 60, maxTime: 120, cost: "free" },
  { id: "stranger-selfie", title: "Stranger Selfie Roulette", description: "Politely ask 5 strangers in {city} for a group selfie. Collect them. Build a stranger photo album together.", category: "Social", spice: 4, minGroup: 2, maxGroup: 8, minTime: 45, maxTime: 90, cost: "free" },
  { id: "story-strangers", title: "Three Stories, Three Strangers", description: "Each person collects a 60-second story from a stranger in {city}. Retell them later at a bar.", category: "Social", spice: 5, minGroup: 2, maxGroup: 6, minTime: 75, maxTime: 150, cost: "$$" },
  { id: "compliment-shuffle", title: "Stranger Compliment Shuffle", description: "Each person finds a stranger in {city} to give a unique one-sentence compliment. Reconvene and trade reactions.", category: "Social", spice: 5, minGroup: 2, maxGroup: 6, minTime: 30, maxTime: 60, cost: "free" },
  { id: "block-party-find", title: "Find a Block Party", description: "Hunt down a block party, market, or street fair happening in {city}. Stay 30 minutes. Make one new friend.", category: "Social", spice: 5, minGroup: 1, maxGroup: 6, minTime: 90, maxTime: 180, cost: "$" },
  { id: "trivia-pop", title: "Pop into Trivia Night", description: "Find a bar with trivia tonight in {city}. Join as a team. Goal: finish in the top half.", category: "Social", spice: 5, minGroup: 2, maxGroup: 6, minTime: 90, maxTime: 180, cost: "$$", lateNight: true, venueQuery: ["bar"] },
  { id: "speed-friend", title: "Speed Friending", description: "Pair up at a cafe in {city}. 5 minutes per pair, 5 rotations. Rate the chats privately at the end.", category: "Social", spice: 4, minGroup: 4, maxGroup: 8, minTime: 60, maxTime: 90, cost: "$", venueQuery: ["cafe"] },
  { id: "language-cafe", title: "Language Cafe Drop-In", description: "Find a language exchange meetup in {city}. Show up. Have a 5-minute chat in any language you barely know.", category: "Social", spice: 5, minGroup: 1, maxGroup: 4, minTime: 90, maxTime: 150, cost: "free" },
  { id: "phone-swap", title: "Phone Swap Hour", description: "For one hour in {city}, swap phones with the person on your left. Reply to texts the way you think they would.", category: "Social", spice: 8, minGroup: 2, maxGroup: 6, minTime: 60, maxTime: 90, cost: "free" },
  { id: "open-mic-watch", title: "Open Mic Witness", description: "Find an open mic in {city}. Stay for 5 acts. Each person tells their favorite performer what they liked.", category: "Social", spice: 5, minGroup: 2, maxGroup: 6, minTime: 90, maxTime: 180, cost: "$$", lateNight: true },
  { id: "small-favor", title: "Small Favor Mission", description: "Do one small unsolicited favor for a stranger in {city} — carry bags, give directions, hold a door. Three each.", category: "Social", spice: 4, minGroup: 2, maxGroup: 6, minTime: 45, maxTime: 90, cost: "free" },
  { id: "two-truths-bus", title: "Two Truths on a Bus Ride", description: "On a bus or train in {city}, play two truths and a lie at audible volume. Get one stranger to overhear and guess.", category: "Social", spice: 6, minGroup: 2, maxGroup: 4, minTime: 45, maxTime: 90, cost: "$" },
  { id: "park-game-recruit", title: "Park Game Recruit", description: "Bring a card or board game to a park in {city}. Recruit at least 2 strangers to join. Play a full round.", category: "Social", spice: 6, minGroup: 2, maxGroup: 4, minTime: 60, maxTime: 120, cost: "free", venueQuery: ["park"] },
  { id: "secret-confidant", title: "Secret Confidant Walk", description: "Walk through {city} in pairs. Each person shares one thing they've never told anyone. Vault rule applies.", category: "Social", spice: 7, minGroup: 4, maxGroup: 6, minTime: 60, maxTime: 90, cost: "free" },
  { id: "5-strangers-question", title: "5 Strangers, 1 Question", description: "Pick one question. Ask 5 strangers in {city}. Average their answers. Compare to your own.", category: "Social", spice: 5, minGroup: 1, maxGroup: 4, minTime: 45, maxTime: 90, cost: "free" },
  { id: "ten-questions-stranger", title: "10 Questions, 1 Stranger", description: "Politely ask one stranger in {city} 10 questions about their life. Buy them a coffee.", category: "Social", spice: 6, minGroup: 1, maxGroup: 3, minTime: 45, maxTime: 90, cost: "$" },
  { id: "busker-tip", title: "Tip a Busker", description: "Find a street musician or busker in {city}. Tip them. Stay for at least one full song.", category: "Social", spice: 3, minGroup: 1, maxGroup: 8, minTime: 20, maxTime: 60, cost: "$" },
  { id: "restaurant-copy-neighbor", title: "Order the Neighbor's Meal", description: "Walk into a restaurant you've never tried in {city}. Order whatever the person at the next table is having.", category: "Social", spice: 6, minGroup: 1, maxGroup: 4, minTime: 60, maxTime: 120, cost: "$$", venueQuery: ["restaurant"] },
  { id: "language-exchange", title: "Language Exchange Mission", description: "Find one stranger in {city} who speaks a language none of you do. Learn 3 words. Use them in your next order.", category: "Social", spice: 4, minGroup: 2, maxGroup: 5, minTime: 45, maxTime: 90, cost: "free" },
  { id: "secret-handshake", title: "Secret Handshake Genesis", description: "Create a 6-step group handshake in {city}. Perform it at 3 different public spots. Teach it to a stranger.", category: "Social", spice: 4, minGroup: 3, maxGroup: 6, minTime: 45, maxTime: 90, cost: "free" },
  { id: "free-event-find", title: "Free Event Crash", description: "Find any free event happening in {city} tonight. Show up. Stay at least 30 minutes. Make one new friend.", category: "Social", spice: 5, minGroup: 1, maxGroup: 6, minTime: 90, maxTime: 180, cost: "free" },
  { id: "rooftop-recon", title: "Rooftop Recon", description: "Roll to {venue} in {city} (or any rooftop bar). Order the most colorful drink on the menu. Toast loudly.", category: "Social", spice: 4, minGroup: 2, maxGroup: 8, minTime: 60, maxTime: 120, cost: "$$$", venueQuery: ["bar"] },
  { id: "karaoke-cold-open", title: "Karaoke Cold Open", description: "Roll to {venue} in {city} (or any karaoke spot). First up sings a song chosen entirely by the group.", category: "Social", spice: 6, minGroup: 2, maxGroup: 8, minTime: 60, maxTime: 180, cost: "$$", lateNight: true, venueQuery: ["bar"] },

  // ===== Creative =====
  { id: "museum-sprint", title: "Museum 90-Min Photo Sprint", description: "Start at {venue} in {city}. Enter and exit 4 museums or galleries within 90 minutes. Photograph one striking thing in each.", category: "Creative", spice: 6, minGroup: 2, maxGroup: 6, minTime: 90, maxTime: 120, cost: "$$", venueQuery: ["museum"] },
  { id: "bookstore-blind-date", title: "Bookstore Blind Date", description: "At a bookstore in {city}, each person picks a book for someone else based on vibes. Read aloud one page together.", category: "Creative", spice: 2, minGroup: 2, maxGroup: 6, minTime: 45, maxTime: 90, cost: "$" },
  { id: "best-pastry", title: "Best Pastry in {city}", description: "Visit 3 bakeries in {city}. One pastry each. Group vote crowns the winner with a paper crown.", category: "Creative", spice: 2, minGroup: 2, maxGroup: 6, minTime: 90, maxTime: 150, cost: "$$" },
  { id: "vintage-photo", title: "Vintage Photo Recreation", description: "Find an old postcard of {city}. Recreate the photo with the group at the exact same location.", category: "Creative", spice: 3, minGroup: 2, maxGroup: 8, minTime: 60, maxTime: 120, cost: "free" },
  { id: "candy-store-blind", title: "Candy Store Blindfold", description: "At a candy store in {city}, one person is blindfolded and picks $5 of candy by feel. The group eats it all.", category: "Creative", spice: 4, minGroup: 2, maxGroup: 6, minTime: 30, maxTime: 60, cost: "$" },
  { id: "vinyl-hunt", title: "Vinyl Hunt", description: "Find a record store in {city}. Each person buys the album with the weirdest cover. Play a track each at home.", category: "Creative", spice: 3, minGroup: 2, maxGroup: 6, minTime: 60, maxTime: 90, cost: "$$" },
  { id: "movie-poster", title: "Movie Poster Group Pose", description: "Pick a famous movie poster. Recreate it at 3 iconic spots around {city}. Best pose wins.", category: "Creative", spice: 4, minGroup: 3, maxGroup: 8, minTime: 60, maxTime: 120, cost: "free" },
  { id: "free-museum-day", title: "Free Museum Speedrun", description: "Hit {venue} in {city} (or any free museum). Speedrun it in 20 minutes. Each person picks their favorite piece.", category: "Creative", spice: 2, minGroup: 1, maxGroup: 8, minTime: 30, maxTime: 60, cost: "free", venueQuery: ["museum"] },
  { id: "chalk-art", title: "Sidewalk Chalk Mural", description: "Buy chalk. Find legal sidewalk space in {city}. Group mural in 30 minutes. Photograph the finished piece.", category: "Creative", spice: 4, minGroup: 2, maxGroup: 8, minTime: 45, maxTime: 90, cost: "$" },
  { id: "alphabet-photo", title: "Alphabet Photo Quest", description: "Photograph 26 things in {city}, one per letter, in alphabetical order. 90-minute limit.", category: "Creative", spice: 4, minGroup: 1, maxGroup: 6, minTime: 90, maxTime: 120, cost: "free" },
  { id: "music-video-shoot", title: "1-Take Music Video", description: "Pick a 90-second song. Choreograph and shoot a one-take music video on the streets of {city}.", category: "Creative", spice: 6, minGroup: 2, maxGroup: 6, minTime: 60, maxTime: 90, cost: "free" },
  { id: "soundtrack-walk", title: "Personal Soundtrack Walk", description: "Each person picks one album. Walk together in {city}. Swap to the next album every time a track ends.", category: "Creative", spice: 2, minGroup: 2, maxGroup: 6, minTime: 60, maxTime: 120, cost: "free" },
  { id: "perfume-blind", title: "Perfume Blind Test", description: "Visit a department store in {city}. Sniff 10 perfumes blind. Each person matches each scent to a memory.", category: "Creative", spice: 3, minGroup: 2, maxGroup: 6, minTime: 45, maxTime: 75, cost: "free" },
  { id: "remix-song", title: "Remix a Song with Sounds", description: "Walk 30 minutes through {city} recording sounds. Cut a 60-second remix of any song using only those clips.", category: "Creative", spice: 4, minGroup: 1, maxGroup: 4, minTime: 60, maxTime: 120, cost: "free" },
  { id: "abandoned-photo", title: "Abandoned-Looking Spot Photoshoot", description: "Find the most abandoned-looking spot in {city} that's still safe and legal. Take a moody group photo there.", category: "Creative", spice: 6, minGroup: 2, maxGroup: 6, minTime: 90, maxTime: 180, cost: "free" },

  // ===== Food =====
  { id: "spice-gauntlet", title: "Spice Gauntlet", description: "Order the spiciest dish on the menu at {venue} in {city}. Everyone takes one bite.", category: "Food", spice: 8, minGroup: 2, maxGroup: 8, minTime: 45, maxTime: 90, cost: "$$", venueQuery: ["restaurant", "fast_food"] },
  { id: "mystery-menu", title: "Mystery Menu", description: "At {venue} in {city}, each person orders for the person across from them. Eat whatever shows up.", category: "Food", spice: 6, minGroup: 2, maxGroup: 8, minTime: 60, maxTime: 120, cost: "$$", venueQuery: ["restaurant"] },
  { id: "menu-translator", title: "Menu Translator", description: "Pick a restaurant in {city} with a menu in another language — try {venue}. Order by pointing.", category: "Food", spice: 5, minGroup: 2, maxGroup: 6, minTime: 60, maxTime: 90, cost: "$$", venueQuery: ["restaurant"] },
  { id: "park-picnic-blind", title: "Blind Picnic", description: "Each person brings one mystery snack to {venue} in {city}. Picnic-style blind taste test. Rank them all.", category: "Food", spice: 3, minGroup: 3, maxGroup: 8, minTime: 45, maxTime: 90, cost: "$", venueQuery: ["park"] },
  { id: "cant-read-menu", title: "Can't-Read-the-Menu Dinner", description: "Eat at a restaurant in {city} where you cannot read the menu. Order by guessing.", category: "Food", spice: 6, minGroup: 2, maxGroup: 6, minTime: 60, maxTime: 120, cost: "$$", venueQuery: ["restaurant"] },
  { id: "five-dollar-dinner", title: "$5 Dinner Challenge", description: "Build a full dinner for the group on $5 each from any grocery in {city}. Eat at the nearest park.", category: "Food", spice: 4, minGroup: 2, maxGroup: 6, minTime: 60, maxTime: 120, cost: "$", venueQuery: ["supermarket"] },
  { id: "single-ingredient", title: "Single-Ingredient Sprint", description: "Pick one weird ingredient. Build a 3-course meal using it in every dish from {city} stores. Cook and eat together.", category: "Food", spice: 5, minGroup: 2, maxGroup: 6, minTime: 120, maxTime: 180, cost: "$$" },
  { id: "blindfold-taste", title: "Blindfold Taste Test", description: "Buy 5 random snacks at a store in {city}. Blindfold each person and taste. Most correct guesses wins.", category: "Food", spice: 4, minGroup: 2, maxGroup: 6, minTime: 30, maxTime: 60, cost: "$" },
  { id: "cuisine-roulette", title: "Cuisine Roulette", description: "Spin for a random cuisine. Find the best version in {city}. Order the most adventurous thing on the menu.", category: "Food", spice: 5, minGroup: 2, maxGroup: 6, minTime: 90, maxTime: 150, cost: "$$", venueQuery: ["restaurant"] },
  { id: "dessert-first", title: "Dessert First Tour", description: "Eat only dessert for one meal across 3 spots in {city}. Score each. Best wins a paper crown.", category: "Food", spice: 3, minGroup: 2, maxGroup: 6, minTime: 90, maxTime: 150, cost: "$$" },
  { id: "five-bites", title: "5 Bites, 5 Cuisines", description: "Five fast bites, five cuisines, one hour in {city}. Smallest plate at each. Photograph every bite.", category: "Food", spice: 5, minGroup: 2, maxGroup: 6, minTime: 60, maxTime: 90, cost: "$$" },
  { id: "weirdest-flavor", title: "Weirdest Flavor Hunt", description: "Find the weirdest flavor combo on sale at any store in {city}. Each person tries one bite. Vote on best and worst.", category: "Food", spice: 5, minGroup: 2, maxGroup: 6, minTime: 60, maxTime: 90, cost: "$" },
  { id: "happy-hour-tour", title: "Happy Hour Tour", description: "Hit 3 happy hours in {city}. One small plate each. Rank them on value-for-money.", category: "Food", spice: 5, minGroup: 2, maxGroup: 6, minTime: 120, maxTime: 180, cost: "$$$", lateNight: true, venueQuery: ["bar"] },
  { id: "cafeteria-mystery", title: "Cafeteria Mystery", description: "Find any cafeteria or canteen in {city}. Grab a tray. Try every item, including the ones you can't identify.", category: "Food", spice: 4, minGroup: 2, maxGroup: 6, minTime: 60, maxTime: 90, cost: "$" },
  { id: "first-thing-special", title: "First Special of the Day", description: "Pick a restaurant in {city}. Order the first special on the menu. Eat it all.", category: "Food", spice: 5, minGroup: 1, maxGroup: 6, minTime: 60, maxTime: 90, cost: "$$", venueQuery: ["restaurant"] },
  { id: "tasting-flight", title: "Tasting Flight Tour", description: "Find any tasting flight in {city} — coffee, beer, tea, sake. Order. Rank from worst to best.", category: "Food", spice: 4, minGroup: 2, maxGroup: 6, minTime: 60, maxTime: 120, cost: "$$" },
  { id: "five-truffles", title: "Top-Shelf Chocolate Five", description: "Find a fancy chocolate shop in {city}. Each person picks one $5 truffle. Blind-taste and rank.", category: "Food", spice: 2, minGroup: 2, maxGroup: 6, minTime: 30, maxTime: 60, cost: "$$" },
  { id: "every-pickle", title: "Every Pickle in the Aisle", description: "Find a grocery in {city}. Buy 3 pickle varieties. Blind taste at a park bench.", category: "Food", spice: 3, minGroup: 2, maxGroup: 6, minTime: 45, maxTime: 75, cost: "$", venueQuery: ["supermarket"] },
  { id: "ice-cream-crawl", title: "Ice Cream Crawl", description: "Hit 3 different ice cream or dessert spots in {city}. One scoop each. Rate them on a chaotic 1-10 scale.", category: "Food", spice: 2, minGroup: 2, maxGroup: 10, minTime: 60, maxTime: 120, cost: "$$" },
  { id: "pizza-slice-standup", title: "Pizza Slice, Standing Up", description: "Find the best-reviewed pizza place within a mile of you in {city}. Order one slice. Eat it standing up outside.", category: "Food", spice: 2, minGroup: 1, maxGroup: 6, minTime: 30, maxTime: 60, cost: "$" },
  { id: "food-truck-special", title: "Food Truck Special", description: "Find the closest food truck or street food vendor in {city}. Order whatever the special is.", category: "Food", spice: 3, minGroup: 1, maxGroup: 6, minTime: 30, maxTime: 60, cost: "$" },
  { id: "coffee-barista-pick", title: "Barista's Pick", description: "Walk into the nearest coffee shop you've never tried in {city}. Order whatever the barista recommends.", category: "Food", spice: 2, minGroup: 1, maxGroup: 6, minTime: 30, maxTime: 60, cost: "$", venueQuery: ["cafe"] },
  { id: "gas-station-snack", title: "Gas Station Mystery Snack", description: "Visit the nearest gas station in {city}. Buy the weirdest snack on the shelf. Share with the group.", category: "Food", spice: 4, minGroup: 1, maxGroup: 6, minTime: 20, maxTime: 45, cost: "$" },
  { id: "convenience-chips", title: "Unusual Chip Hunt", description: "Find the nearest convenience store in {city}. Buy the most unusual flavor of chips they carry. Group taste test.", category: "Food", spice: 3, minGroup: 2, maxGroup: 6, minTime: 20, maxTime: 45, cost: "$" },
  { id: "dollar-five-items", title: "Dollar Store Build-A-Thing", description: "Go to the nearest dollar store in {city}. Buy 5 random items. Build something out of them together.", category: "Food", spice: 4, minGroup: 2, maxGroup: 6, minTime: 45, maxTime: 90, cost: "$" },

  // ===== Late Night =====
  { id: "midnight-photo-walk", title: "Midnight Photo Walk", description: "Walk through {city} from midnight to 1am. Each person shoots 5 long-exposure photos. Best one gets framed.", category: "Late Night", spice: 5, minGroup: 1, maxGroup: 6, minTime: 60, maxTime: 90, cost: "free", lateNight: true },
  { id: "all-night-diner", title: "Pancakes at 3AM", description: "Find a 24-hour spot in {city}. Order only pancakes. Pick a topic and debate it until sunrise.", category: "Late Night", spice: 6, minGroup: 2, maxGroup: 6, minTime: 90, maxTime: 180, cost: "$$", lateNight: true, venueQuery: ["restaurant"] },
  { id: "neon-tour", title: "Neon Sign Hunt", description: "After dark in {city}, photograph 10 neon signs. Vote on the most iconic. Eat at the place under it.", category: "Late Night", spice: 4, minGroup: 1, maxGroup: 6, minTime: 90, maxTime: 150, cost: "$$", lateNight: true },
  { id: "after-dark-bookstore", title: "After-Dark Bookstore", description: "Find a late-open bookstore in {city}. Each person picks a book by cover alone. Read 10 pages aloud as a group.", category: "Late Night", spice: 3, minGroup: 2, maxGroup: 6, minTime: 60, maxTime: 90, cost: "$$", lateNight: true },
  { id: "secret-bar", title: "Speakeasy Recon", description: "Hunt down a hidden or speakeasy-style bar in {city}. Order the bartender's choice. Tip well.", category: "Late Night", spice: 6, minGroup: 2, maxGroup: 4, minTime: 90, maxTime: 150, cost: "$$$", lateNight: true, venueQuery: ["bar"] },
  { id: "late-grocery-snack", title: "Midnight Grocery Snack Run", description: "Hit any open grocery in {city} after 11pm. $7 each on impulse buys. Reconvene and rank everything.", category: "Late Night", spice: 4, minGroup: 2, maxGroup: 6, minTime: 30, maxTime: 60, cost: "$", lateNight: true, venueQuery: ["supermarket"] },
  { id: "moon-cinema", title: "Moonlit Mini Cinema", description: "Stream a 30-minute short on a phone or laptop on a rooftop or open space in {city} after midnight.", category: "Late Night", spice: 4, minGroup: 2, maxGroup: 6, minTime: 60, maxTime: 90, cost: "free", lateNight: true },
  { id: "dawn-pancakes", title: "Pre-Dawn Coffee Run", description: "Be at {venue} in {city} (a 24-hour cafe) by 4:30am. Order. Watch the city wake up.", category: "Late Night", spice: 6, minGroup: 1, maxGroup: 6, minTime: 60, maxTime: 90, cost: "$", lateNight: true, venueQuery: ["cafe"] },
  { id: "karaoke-bar-roll", title: "Karaoke Bar Roll", description: "Find a karaoke spot in {city}. Each person sings one song chosen by the group.", category: "Late Night", spice: 8, minGroup: 2, maxGroup: 6, minTime: 90, maxTime: 180, cost: "$$", lateNight: true, venueQuery: ["bar"] },
  { id: "stargazing-park", title: "Park-Bench Stargaze", description: "Find a quiet bench at a park in {city} after dark. Stay 30 minutes. Count satellites.", category: "Late Night", spice: 3, minGroup: 2, maxGroup: 6, minTime: 30, maxTime: 60, cost: "free", lateNight: true, venueQuery: ["park"] },
  { id: "after-hours-photoshoot", title: "After-Hours Fashion Shoot", description: "Wear your most dramatic outfit at midnight in {city}. Photograph each other under streetlights for 30 minutes.", category: "Late Night", spice: 7, minGroup: 2, maxGroup: 6, minTime: 45, maxTime: 75, cost: "free", lateNight: true },
  { id: "midnight-snack-quest", title: "Midnight Snack Quest", description: "After midnight, head to {venue} in {city} (or any open food spot you find strange). Order whatever the cashier recommends.", category: "Late Night", spice: 6, minGroup: 2, maxGroup: 6, minTime: 45, maxTime: 90, cost: "$", lateNight: true, venueQuery: ["fast_food", "restaurant"] },
  { id: "diner-deep-talk", title: "Diner Deep Talk", description: "Post up at {venue} in {city} (or any late-night diner). Order fries. Each person answers one question they've never answered honestly.", category: "Late Night", spice: 5, minGroup: 2, maxGroup: 6, minTime: 60, maxTime: 120, cost: "$$", lateNight: true, venueQuery: ["restaurant", "fast_food"] },
  { id: "wildcard-bartender", title: "Wildcard Bartender", description: "At {venue} in {city}, give the bartender three adjectives. Drink whatever they make for you.", category: "Late Night", spice: 7, minGroup: 2, maxGroup: 6, minTime: 45, maxTime: 90, cost: "$$", lateNight: true, venueQuery: ["bar"] },
  { id: "playground-tag", title: "Adult Tag", description: "Meet at {venue} in {city}. Play one full round of tag. Wear whatever you're already wearing.", category: "Outdoor", spice: 5, minGroup: 4, maxGroup: 10, minTime: 30, maxTime: 60, cost: "free", venueQuery: ["park", "playground"] },

  // ===== Chill =====
  { id: "notice-walk", title: "10-Minute Notice Walk", description: "Walk for 10 minutes around {city}. Each person spots 5 things they've never noticed before. Compare lists.", category: "Chill", spice: 1, minGroup: 1, maxGroup: 6, minTime: 10, maxTime: 20, cost: "free" },
  { id: "library-hideout", title: "Library Hideout", description: "Find a quiet library corner in {city}. Read for 30 minutes. Trade favorite passages over coffee after.", category: "Chill", spice: 1, minGroup: 1, maxGroup: 4, minTime: 30, maxTime: 60, cost: "free", venueQuery: ["library"] },
  { id: "phone-stash", title: "Phone Stash Hour", description: "Stash phones in a bag at a cafe in {city} for one hour. First to reach for theirs buys the next round.", category: "Chill", spice: 3, minGroup: 2, maxGroup: 8, minTime: 60, maxTime: 90, cost: "$", venueQuery: ["cafe"] },
  { id: "song-of-the-year", title: "Song of the Year Swap", description: "At a quiet spot in {city}, each person plays one song that defines this year for them. Listen all the way through.", category: "Chill", spice: 2, minGroup: 2, maxGroup: 6, minTime: 30, maxTime: 60, cost: "free" },
  { id: "sunset-claim", title: "Sunset Claim", description: "Find the best free sunset view in {city}. Arrive 20 minutes early. Stay until full dark.", category: "Chill", spice: 1, minGroup: 1, maxGroup: 8, minTime: 45, maxTime: 90, cost: "free", venueQuery: ["viewpoint"] },
  { id: "playlist-trade", title: "Playlist Trade", description: "Make each other 5-track playlists on the spot from a cafe in {city}. Trade. Listen on the walk home.", category: "Chill", spice: 1, minGroup: 2, maxGroup: 4, minTime: 30, maxTime: 60, cost: "$", venueQuery: ["cafe"] },
  { id: "favorite-block", title: "Favorite Block Walk", description: "Each person picks their favorite block within walking distance in {city}. Tour all of them.", category: "Chill", spice: 1, minGroup: 2, maxGroup: 6, minTime: 60, maxTime: 120, cost: "free" },
  { id: "memory-recall-walk", title: "Memory-Recall Walk", description: "Walk through {city} swapping childhood memories. Funniest one buys coffee.", category: "Chill", spice: 2, minGroup: 2, maxGroup: 6, minTime: 30, maxTime: 60, cost: "$" },
  { id: "tea-ceremony", title: "DIY Tea Ceremony", description: "Hit a tea shop in {city}. Buy one tea each based purely on the name. Brew them all at someone's place.", category: "Chill", spice: 2, minGroup: 2, maxGroup: 6, minTime: 60, maxTime: 90, cost: "$" },
  { id: "puzzle-cafe", title: "Cafe Puzzle Race", description: "Bring or buy a 100-piece puzzle to a cafe in {city}. Race solo or in pairs. Winner picks the next quest.", category: "Chill", spice: 3, minGroup: 2, maxGroup: 6, minTime: 60, maxTime: 120, cost: "$", venueQuery: ["cafe"] },

  // ===== Fitness =====
  { id: "stair-king", title: "Stair King", description: "Find the longest public staircase in {city}. Race to the top. Loser does 10 pushups at the bottom.", category: "Fitness", spice: 6, minGroup: 2, maxGroup: 6, minTime: 30, maxTime: 60, cost: "free" },
  { id: "5k-blitz", title: "Surprise 5K", description: "Pick a starting line in {city}. Run or walk 5K however slow. At the finish, take a finisher pic.", category: "Fitness", spice: 5, minGroup: 1, maxGroup: 10, minTime: 30, maxTime: 90, cost: "free" },
  { id: "pull-up-park", title: "Pull-Up Park Tour", description: "Find 3 outdoor fitness setups in {city}. Each person does as many pull-ups as they can at each. Highest total wins.", category: "Fitness", spice: 5, minGroup: 2, maxGroup: 6, minTime: 60, maxTime: 90, cost: "free", venueQuery: ["park"] },
  { id: "yoga-anywhere", title: "Yoga Anywhere", description: "Do a 20-minute yoga flow at the weirdest legal spot in {city}. Photograph one pose at peak.", category: "Fitness", spice: 4, minGroup: 1, maxGroup: 8, minTime: 30, maxTime: 60, cost: "free" },
  { id: "bike-100min", title: "100-Minute Bike Tour", description: "Rent or bring bikes in {city}. Ride 100 minutes nonstop along the best route you can scout.", category: "Fitness", spice: 5, minGroup: 1, maxGroup: 6, minTime: 100, maxTime: 150, cost: "$$" },
  { id: "hike-up", title: "Hike Until You Can't", description: "Pick a trail or hill near {city}. Hike up until someone calls it. Take a peak photo.", category: "Fitness", spice: 6, minGroup: 1, maxGroup: 8, minTime: 90, maxTime: 240, cost: "free" },
  { id: "swim-find", title: "Find a Body of Water", description: "Locate any swimmable body of water near {city} — pool, lake, ocean. Dip in for at least 60 seconds.", category: "Fitness", spice: 6, minGroup: 2, maxGroup: 8, minTime: 90, maxTime: 240, cost: "$" },
  { id: "plank-bet", title: "Plank Bet", description: "Find a flat surface in {city}. Plank competition. Loser pays for everyone's next drink.", category: "Fitness", spice: 5, minGroup: 2, maxGroup: 6, minTime: 15, maxTime: 30, cost: "free" },
  { id: "stadium-stairs", title: "Stadium Stair Sprints", description: "Find stadium or arena steps near {city}. Run up and down 10 times each. Last finisher buys recovery snacks.", category: "Fitness", spice: 7, minGroup: 2, maxGroup: 8, minTime: 45, maxTime: 90, cost: "free", venueQuery: ["stadium"] },
  { id: "dance-class-crash", title: "Dance Class Crash", description: "Find any drop-in dance class in {city}. Attend together. Most enthusiastic dancer wins glory.", category: "Fitness", spice: 6, minGroup: 2, maxGroup: 6, minTime: 60, maxTime: 120, cost: "$$" },
  { id: "boxing-shadow", title: "Shadow Boxing Round", description: "Find a public park in {city}. Each person does 3 minutes of shadow boxing while the others cheer.", category: "Fitness", spice: 5, minGroup: 2, maxGroup: 8, minTime: 20, maxTime: 45, cost: "free", venueQuery: ["park"] },
  { id: "sprint-corner", title: "Corner Sprint", description: "Pick a city block in {city}. Race to the corner. Best of three.", category: "Fitness", spice: 5, minGroup: 2, maxGroup: 6, minTime: 10, maxTime: 20, cost: "free" },
  { id: "climbing-wall", title: "Bouldering First-Timer", description: "Find a climbing gym in {city}. Each person attempts 3 routes. Hardest send earns bragging rights.", category: "Fitness", spice: 5, minGroup: 1, maxGroup: 6, minTime: 90, maxTime: 180, cost: "$$", venueQuery: ["sports_centre"] },
  { id: "kickball-comeback", title: "Park Kickball", description: "Bring a ball to a park in {city}. Recruit 1 stranger to join. Play one inning.", category: "Fitness", spice: 6, minGroup: 4, maxGroup: 10, minTime: 60, maxTime: 90, cost: "$", venueQuery: ["park"] },
  { id: "morning-jog-cap", title: "5AM Jog Cap", description: "Meet at 5AM in {city}. Run or walk 30 minutes. Photograph the sunrise. Brunch follows.", category: "Fitness", spice: 7, minGroup: 2, maxGroup: 8, minTime: 60, maxTime: 120, cost: "$" },

  // ===== Nature =====
  { id: "oldest-tree", title: "Find the Oldest Tree", description: "Find what looks like the oldest tree near {city}. Estimate its age by trunk size. Photograph the group with it.", category: "Nature", spice: 2, minGroup: 1, maxGroup: 6, minTime: 60, maxTime: 120, cost: "free", venueQuery: ["park"] },
  { id: "bird-bingo", title: "Bird Bingo", description: "Build a bingo card of 9 likely birds in {city}. Spend 90 minutes spotting. First to bingo buys coffee.", category: "Nature", spice: 2, minGroup: 2, maxGroup: 6, minTime: 90, maxTime: 120, cost: "$", venueQuery: ["park"] },
  { id: "sunrise-spot", title: "Sunrise Hunt", description: "Find an east-facing public spot in {city}. Show up before dawn. Stay until the sun clears the horizon.", category: "Nature", spice: 4, minGroup: 1, maxGroup: 8, minTime: 60, maxTime: 90, cost: "free" },
  { id: "moonwalk", title: "Full-Moon Walk", description: "On the next full moon, walk for an hour through {city}. Each person shares one wish along the way.", category: "Nature", spice: 3, minGroup: 2, maxGroup: 8, minTime: 60, maxTime: 90, cost: "free", lateNight: true },
  { id: "river-find", title: "Source of the Water", description: "Find any flowing water in {city}. Follow it as far as you can on foot. Take a group photo at the end.", category: "Nature", spice: 4, minGroup: 1, maxGroup: 6, minTime: 90, maxTime: 180, cost: "free" },
  { id: "stargaze", title: "Stargaze From a Dark Spot", description: "Find the darkest publicly accessible spot near {city}. Stay 30 minutes. Count shooting stars.", category: "Nature", spice: 3, minGroup: 1, maxGroup: 8, minTime: 60, maxTime: 120, cost: "free", lateNight: true, venueQuery: ["viewpoint"] },
  { id: "flower-snap", title: "Flower Snap Speedrun", description: "Photograph 15 different flowers or plants in {city} within 60 minutes. Identify them with an app at the end.", category: "Nature", spice: 2, minGroup: 1, maxGroup: 4, minTime: 60, maxTime: 90, cost: "free" },
  { id: "barefoot-grass", title: "10 Minutes Barefoot", description: "Find clean grass at a park in {city}. Shoes off for 10 minutes. Each person shares one childhood memory.", category: "Nature", spice: 2, minGroup: 1, maxGroup: 8, minTime: 10, maxTime: 30, cost: "free", venueQuery: ["park"] },
  { id: "tide-pool", title: "Tide Pool or Stream Survey", description: "Find a stream or shoreline near {city}. Count distinct living things you can see in 20 minutes.", category: "Nature", spice: 3, minGroup: 1, maxGroup: 6, minTime: 45, maxTime: 90, cost: "free" },
  { id: "wildlife-watch", title: "Wildlife Watch", description: "Sit still at a green space in {city} for 30 minutes. Photograph the most interesting living thing you spot.", category: "Nature", spice: 2, minGroup: 1, maxGroup: 4, minTime: 30, maxTime: 60, cost: "free", venueQuery: ["park"] },
  { id: "compost-mission", title: "Compost Mission", description: "Find a community garden or composting site in {city}. Volunteer for an hour. Take a dirt selfie.", category: "Nature", spice: 3, minGroup: 1, maxGroup: 6, minTime: 60, maxTime: 120, cost: "free" },
  { id: "trash-cleanup", title: "Mini Cleanup", description: "Bring gloves and a bag. Pick up trash on one block in {city} for 30 minutes. Photograph the haul at the end.", category: "Nature", spice: 3, minGroup: 1, maxGroup: 8, minTime: 30, maxTime: 60, cost: "free" },
  { id: "cloud-photo", title: "Best Cloud Photo", description: "60 minutes in {city}. Each person captures one cloud photo. Group votes on the most striking shot.", category: "Nature", spice: 1, minGroup: 2, maxGroup: 8, minTime: 60, maxTime: 90, cost: "free" },

  // ===== Tech =====
  { id: "ai-portrait", title: "AI Portrait Hunt", description: "In {city}, each person finds something IRL that matches an AI-generated image you all agree on. First match wins.", category: "Tech", spice: 5, minGroup: 2, maxGroup: 6, minTime: 60, maxTime: 120, cost: "free" },
  { id: "qr-treasure", title: "QR Treasure", description: "One person hides 5 QR codes around {city} pointing to absurd memes. Everyone else hunts and screenshots.", category: "Tech", spice: 6, minGroup: 3, maxGroup: 8, minTime: 90, maxTime: 150, cost: "free" },
  { id: "ai-restaurant", title: "AI-Picked Restaurant", description: "Ask any AI to pick a restaurant in {city}. Go. Follow its ordering recommendation exactly.", category: "Tech", spice: 5, minGroup: 2, maxGroup: 6, minTime: 60, maxTime: 120, cost: "$$", venueQuery: ["restaurant"] },
  { id: "geocache", title: "Geocache Hunt", description: "Open a geocaching app. Find at least one cache within {city}. Sign the log if you find it.", category: "Tech", spice: 4, minGroup: 1, maxGroup: 6, minTime: 60, maxTime: 120, cost: "free" },
  { id: "yelp-bottom", title: "Yelp Bottom-Rated", description: "Find the lowest-rated open restaurant in {city} on Yelp. Order one item. Decide together if the rating is fair.", category: "Tech", spice: 7, minGroup: 2, maxGroup: 5, minTime: 60, maxTime: 90, cost: "$", venueQuery: ["restaurant", "fast_food"] },
  { id: "ai-name-quest", title: "AI Names the Quest", description: "Ask an AI to generate a quest for {city} for your group size. Do whatever it says (within reason).", category: "Tech", spice: 7, minGroup: 2, maxGroup: 6, minTime: 60, maxTime: 180, cost: "$" },
  { id: "wikipedia-roulette", title: "Wikipedia Roulette", description: "Hit Wikipedia's Random Article 3 times. Pick the one with the closest {city} tie-in. Visit a related place.", category: "Tech", spice: 4, minGroup: 1, maxGroup: 6, minTime: 60, maxTime: 120, cost: "free" },
  { id: "smart-home-demo", title: "Gadget Demo Crash", description: "Walk into any electronics store in {city}. Get a 5-minute tour of a new gadget from an employee.", category: "Tech", spice: 5, minGroup: 1, maxGroup: 4, minTime: 30, maxTime: 60, cost: "free" },
  { id: "podcast-record", title: "10-Minute Podcast Record", description: "Find an interesting bench in {city}. Record a 10-minute podcast riffing on what you see. Publish or trash it.", category: "Tech", spice: 4, minGroup: 2, maxGroup: 4, minTime: 30, maxTime: 60, cost: "free" },
  { id: "drone-photo", title: "Drone-Style Group Shot", description: "Find the highest legal vantage in {city}. Get a top-down group photo. Bonus: actual drone if allowed.", category: "Tech", spice: 4, minGroup: 2, maxGroup: 10, minTime: 60, maxTime: 120, cost: "free", venueQuery: ["viewpoint"] },
  { id: "ai-photo-caption", title: "Reverse Photo Caption", description: "Take one weird photo in {city}. Ask AI to caption it. Group picks the funniest caption.", category: "Tech", spice: 3, minGroup: 2, maxGroup: 6, minTime: 30, maxTime: 45, cost: "free" },

  // ===== Exploration =====
  { id: "unknown-neighborhood", title: "Unknown Neighborhood Drop", description: "Pick a neighborhood in {city} none of you has ever set foot in. Spend 90 minutes exploring it on foot.", category: "Exploration", spice: 4, minGroup: 1, maxGroup: 6, minTime: 90, maxTime: 150, cost: "$" },
  { id: "every-floor", title: "Every Floor of a Tall Building", description: "Find a public-access tall building in {city}. Visit every floor with public access. Take a photo on each.", category: "Exploration", spice: 5, minGroup: 1, maxGroup: 4, minTime: 60, maxTime: 120, cost: "free" },
  { id: "30-block-mile", title: "30-Block Mile", description: "Pick a starting point in {city}. Walk a full mile. Stop at the 30th most interesting thing you see.", category: "Exploration", spice: 3, minGroup: 1, maxGroup: 6, minTime: 60, maxTime: 90, cost: "free" },
  { id: "every-train", title: "Every Train Line, One Stop", description: "Ride every train or bus line in {city} for exactly one stop. Document the line names.", category: "Exploration", spice: 6, minGroup: 1, maxGroup: 4, minTime: 120, maxTime: 240, cost: "$" },
  { id: "alleyway-tour", title: "Alleyway Tour", description: "Walk only down alleys in {city} for 45 minutes (where legal and safe). Photograph the strangest thing you spot.", category: "Exploration", spice: 5, minGroup: 2, maxGroup: 4, minTime: 45, maxTime: 90, cost: "free" },
  { id: "highest-public-place", title: "Highest Public Point", description: "Find the highest publicly accessible point in {city}. Shoot a panoramic video at the top.", category: "Exploration", spice: 4, minGroup: 1, maxGroup: 8, minTime: 60, maxTime: 120, cost: "free", venueQuery: ["viewpoint"] },
  { id: "lowest-public-place", title: "Lowest Public Point", description: "Find the lowest publicly accessible place in {city} — basement, underpass, subway tunnel. Sit for 5 minutes.", category: "Exploration", spice: 4, minGroup: 2, maxGroup: 6, minTime: 30, maxTime: 60, cost: "free" },
  { id: "neighborhood-landmark", title: "Neighborhood Landmark", description: "Pick a neighborhood in {city}. Find its most iconic landmark, animal, statue, or sign. Photograph it.", category: "Exploration", spice: 3, minGroup: 2, maxGroup: 6, minTime: 60, maxTime: 90, cost: "free" },
  { id: "compass-walk", title: "Compass Walk North", description: "Open a compass app. Walk due north from where you are in {city} for 30 minutes. Re-route only when blocked.", category: "Exploration", spice: 5, minGroup: 1, maxGroup: 4, minTime: 45, maxTime: 90, cost: "free" },
  { id: "transit-roulette", title: "Transit Roulette", description: "Take the next bus or train leaving {city}'s nearest stop. Get off at the 5th stop. Find dinner within a 10-minute walk.", category: "Exploration", spice: 7, minGroup: 1, maxGroup: 6, minTime: 90, maxTime: 180, cost: "$$" },
  { id: "find-the-fountain", title: "Find Every Fountain", description: "Find every public fountain within walking distance in {city}. Photograph each. Coin toss in the best one.", category: "Exploration", spice: 3, minGroup: 1, maxGroup: 6, minTime: 60, maxTime: 120, cost: "$" },
  { id: "library-floor-scan", title: "Library Floor Scan", description: "Walk every floor of the largest library in {city}. Bring back one weird book each to read at a cafe.", category: "Exploration", spice: 2, minGroup: 1, maxGroup: 4, minTime: 60, maxTime: 90, cost: "free", venueQuery: ["library"] },
  { id: "free-tour-crash", title: "Free Walking Tour Crash", description: "Find a free walking tour happening in {city}. Tag along or run one yourselves for tourists.", category: "Exploration", spice: 5, minGroup: 2, maxGroup: 6, minTime: 90, maxTime: 180, cost: "free" },
  { id: "smell-map", title: "Smell Map of the City", description: "Walk 1 mile in {city}. Each person tracks 10 distinct smells with where they noticed each. Compare maps after.", category: "Exploration", spice: 3, minGroup: 1, maxGroup: 4, minTime: 60, maxTime: 90, cost: "free" },
  { id: "sound-walk", title: "Sound Walk", description: "Walk 30 minutes through {city} listening closely. Identify 20 distinct sounds. Compare lists at the end.", category: "Exploration", spice: 2, minGroup: 1, maxGroup: 6, minTime: 30, maxTime: 60, cost: "free" },
  { id: "lost-on-purpose", title: "Lost on Purpose", description: "Turn off GPS in {city}. Walk 30 minutes without a destination. Find your way back asking people only.", category: "Exploration", spice: 7, minGroup: 2, maxGroup: 4, minTime: 60, maxTime: 120, cost: "free" },
  { id: "oldest-building", title: "Oldest Building Guess", description: "Find the oldest-looking building near you in {city}. Guess its construction year. Look it up afterward.", category: "Exploration", spice: 2, minGroup: 1, maxGroup: 6, minTime: 45, maxTime: 90, cost: "free" },
  { id: "hardware-mystery-buy", title: "Hardware Store Mystery Buy", description: "Go to the nearest hardware store in {city}. Buy one random thing under $5. Figure out what to do with it together.", category: "Exploration", spice: 4, minGroup: 2, maxGroup: 6, minTime: 45, maxTime: 90, cost: "$" },
  { id: "thrift-ridiculous", title: "Most Ridiculous Thrift Buy", description: "Go to the nearest thrift store in {city}. Each person buys the most ridiculous item under $10. Show and tell.", category: "Exploration", spice: 5, minGroup: 2, maxGroup: 6, minTime: 60, maxTime: 90, cost: "$$" },
  { id: "rooftop-view-pano", title: "Rooftop Panoramic", description: "Find the closest rooftop or elevated spot in {city} with a view. Shoot a panoramic video from the top.", category: "Exploration", spice: 4, minGroup: 1, maxGroup: 6, minTime: 45, maxTime: 90, cost: "free", venueQuery: ["viewpoint"] },
  { id: "bookstore-random-page", title: "Bookstore Random Page", description: "Find the closest bookstore or library in {city}. Pick a book at random. Read the first page out loud as a group.", category: "Exploration", spice: 2, minGroup: 2, maxGroup: 6, minTime: 30, maxTime: 60, cost: "free", venueQuery: ["library"] },
  { id: "farmers-market-five", title: "Farmers Market Five", description: "Hit any farmers market or open market in {city}. Each person buys $5 of one ingredient. Cook lunch together later.", category: "Food", spice: 3, minGroup: 2, maxGroup: 6, minTime: 90, maxTime: 150, cost: "$$" },
  { id: "coffee-shop-tour", title: "Coffee Shop Tour", description: "Hit 3 different coffee shops within walking distance in {city}. Order the same drink at each. Rank them.", category: "Food", spice: 2, minGroup: 1, maxGroup: 6, minTime: 90, maxTime: 150, cost: "$$", venueQuery: ["cafe"] },
  { id: "free-museum-tour", title: "Docent-Led Free Tour", description: "Find a free docent-led tour at any museum in {city}. Show up. Stay through the whole thing.", category: "Creative", spice: 2, minGroup: 1, maxGroup: 6, minTime: 60, maxTime: 120, cost: "free", venueQuery: ["museum"] },
  { id: "neighborhood-three-blocks", title: "Three Blocks, Three Strangers", description: "Walk 3 blocks in {city}. On each block, ask one stranger for their favorite spot within 5 minutes' walk. Hit all three.", category: "Social", spice: 5, minGroup: 1, maxGroup: 4, minTime: 60, maxTime: 120, cost: "$$" },
  { id: "art-gallery-pop", title: "Art Gallery Pop-In", description: "Find a free art gallery in {city}. Spend 20 minutes. Each person picks one piece they'd hang at home.", category: "Creative", spice: 2, minGroup: 1, maxGroup: 6, minTime: 30, maxTime: 60, cost: "free", venueQuery: ["museum"] },
  { id: "outdoor-stretch", title: "10-Minute Outdoor Stretch", description: "Find a quiet patch of grass at a park in {city}. Lead each other through a 10-minute stretch routine.", category: "Fitness", spice: 2, minGroup: 2, maxGroup: 6, minTime: 15, maxTime: 30, cost: "free", venueQuery: ["park"] },
  { id: "fast-food-mystery", title: "Fast Food Mystery Order", description: "At {venue} in {city}, each person closes their eyes and points at the menu. Order whatever they land on.", category: "Food", spice: 5, minGroup: 2, maxGroup: 6, minTime: 30, maxTime: 60, cost: "$", venueQuery: ["fast_food"] },
  { id: "downtown-zigzag", title: "Downtown Zigzag", description: "Pick downtown {city}. Walk a strict zigzag pattern (left, right, left, right) for 45 minutes. End wherever you end.", category: "Exploration", spice: 4, minGroup: 1, maxGroup: 6, minTime: 45, maxTime: 90, cost: "free" },
  { id: "weekend-festival-find", title: "Weekend Festival Find", description: "Search what events are happening in {city} this weekend. Pick the one with the strangest description. Go.", category: "Social", spice: 5, minGroup: 1, maxGroup: 6, minTime: 120, maxTime: 240, cost: "$$" },
];
