export type QuestCategory =
  | "Chaos"
  | "Outdoor"
  | "Social"
  | "Creative"
  | "Food"
  | "Late Night"
  | "Chill"
  | "Fitness"
  | "Nature"
  | "Tech"
  | "Exploration";

export type QuestCost = "free" | "$" | "$$" | "$$$";

export type QuestTemplate = {
  id: string;
  title: string;
  description: string;
  category: QuestCategory;
  spice: number; // 1-10
  minGroup: number;
  maxGroup: number;
  minTime: number; // minutes
  maxTime: number;
  cost?: QuestCost;
  lateNight?: boolean;
  // OSM tag values to look for if we have nearby-place data. If a match is
  // found, {venue} in title/description is replaced with the real venue name.
  venueQuery?: string[];
};

// {city} is substituted with the user's location at generation time.
export const QUESTS: QuestTemplate[] = [
  {
    id: "stranger-compliments",
    title: "Stranger Compliment Chain",
    description:
      "Each person must give a genuine compliment to 5 strangers in {city}. Bonus: get one to compliment you back.",
    category: "Social",
    spice: 4,
    minGroup: 2,
    maxGroup: 10,
    minTime: 30,
    maxTime: 90,
  },
  {
    id: "weirdest-cart",
    title: "1am Weirdest-Cart Audit",
    description:
      "Hit {venue} in {city} (or any 24-hour store). Fill one shared cart with the weirdest items under $3 each. Pay together at checkout.",
    category: "Late Night",
    spice: 7,
    minGroup: 2,
    maxGroup: 6,
    minTime: 45,
    maxTime: 90,
    lateNight: true,
    venueQuery: ["supermarket"],
  },
  {
    id: "tech-meetup-chaos",
    title: "Tech Meetup Chaos Questions",
    description:
      "Crash a real startup/tech meetup in {city}. Each person must get a founder to seriously answer one absurd question.",
    category: "Social",
    spice: 5,
    minGroup: 2,
    maxGroup: 5,
    minTime: 60,
    maxTime: 150,
  },
  {
    id: "museum-sprint",
    title: "Museum 90-Min Photo Sprint",
    description:
      "Start at {venue} in {city}. No GPS. Enter and exit 4 museums or galleries within 90 minutes. Photograph the weirdest object in each.",
    category: "Creative",
    spice: 6,
    minGroup: 2,
    maxGroup: 6,
    minTime: 90,
    maxTime: 120,
    venueQuery: ["museum"],
  },
  {
    id: "bus-roulette",
    title: "Bus Roulette",
    description:
      "Board the next bus or train leaving {city}'s nearest stop. Ride 4 stops. Get off. Find food within 10 minutes.",
    category: "Chaos",
    spice: 6,
    minGroup: 1,
    maxGroup: 8,
    minTime: 60,
    maxTime: 180,
  },
  {
    id: "park-bench-philosophers",
    title: "Park Bench Philosophers",
    description:
      "Head to {venue} in {city}. Sit on different benches. Strike up 3-minute philosophy conversations with anyone nearby.",
    category: "Outdoor",
    spice: 3,
    minGroup: 2,
    maxGroup: 6,
    minTime: 45,
    maxTime: 90,
    venueQuery: ["park"],
  },
  {
    id: "fake-tourist",
    title: "Fake Tourist Mode",
    description:
      "Pretend you've never been to {city}. Ask locals for the 'best hidden spot.' Follow the top 3 recommendations.",
    category: "Social",
    spice: 4,
    minGroup: 2,
    maxGroup: 5,
    minTime: 90,
    maxTime: 180,
  },
  {
    id: "dollar-store-gifts",
    title: "Dollar Store Gift Exchange",
    description:
      "Everyone gets $5 at a dollar store in {city}. Buy gifts blindly for each other. Reveal at the nearest coffee shop.",
    category: "Creative",
    spice: 3,
    minGroup: 3,
    maxGroup: 8,
    minTime: 45,
    maxTime: 75,
  },
  {
    id: "karaoke-cold-open",
    title: "Karaoke Cold Open",
    description:
      "Roll to {venue} in {city} (or any karaoke spot). First person up sings a song chosen entirely by the group. No vetoes.",
    category: "Late Night",
    spice: 6,
    minGroup: 2,
    maxGroup: 8,
    minTime: 60,
    maxTime: 180,
    lateNight: true,
    venueQuery: ["bar"],
  },
  {
    id: "skyline-hunt",
    title: "Skyline Hunt",
    description:
      "Make for {venue} in {city} (or the highest publicly accessible vantage point you can find). Take a group photo at the top.",
    category: "Outdoor",
    spice: 4,
    minGroup: 1,
    maxGroup: 8,
    minTime: 60,
    maxTime: 120,
    venueQuery: ["viewpoint", "attraction"],
  },
  {
    id: "open-mic-dare",
    title: "Open Mic Dare",
    description:
      "Find an open mic in {city} tonight. One member of the group must perform. Audience picks the topic on the spot.",
    category: "Chaos",
    spice: 9,
    minGroup: 2,
    maxGroup: 6,
    minTime: 90,
    maxTime: 180,
    lateNight: true,
  },
  {
    id: "thrift-outfit",
    title: "Thrift Outfit Swap",
    description:
      "$10 each at a thrift store in {city}. Pick out an entire outfit for the person on your left. Must wear it all day.",
    category: "Creative",
    spice: 5,
    minGroup: 3,
    maxGroup: 8,
    minTime: 75,
    maxTime: 120,
  },
  {
    id: "ice-cream-crawl",
    title: "Ice Cream Crawl",
    description:
      "Hit 3 different ice cream/dessert spots in {city}. One scoop each, rate on a chaotic 1-10 scale.",
    category: "Food",
    spice: 2,
    minGroup: 2,
    maxGroup: 10,
    minTime: 60,
    maxTime: 120,
  },
  {
    id: "spice-gauntlet",
    title: "Spice Gauntlet",
    description:
      "Hit {venue} in {city}. Order the spiciest dish on the menu. Everyone takes one bite. No drinks for 60 seconds.",
    category: "Food",
    spice: 8,
    minGroup: 2,
    maxGroup: 8,
    minTime: 45,
    maxTime: 90,
    venueQuery: ["restaurant", "fast_food"],
  },
  {
    id: "diner-deep-talk",
    title: "Diner Deep Talk",
    description:
      "Post up at {venue} in {city} (or any late-night diner). Order fries. Each person answers one question they've never answered honestly.",
    category: "Late Night",
    spice: 5,
    minGroup: 2,
    maxGroup: 6,
    minTime: 60,
    maxTime: 120,
    lateNight: true,
    venueQuery: ["restaurant", "fast_food"],
  },
  {
    id: "playground-takeover",
    title: "Playground Takeover (Legal)",
    description:
      "Meet at {venue} in {city}. Hold a 10-minute swing competition. Loser buys snacks.",
    category: "Outdoor",
    spice: 3,
    minGroup: 2,
    maxGroup: 6,
    minTime: 30,
    maxTime: 60,
    venueQuery: ["playground"],
  },
  {
    id: "mystery-menu",
    title: "Mystery Menu",
    description:
      "At {venue} in {city}, each person orders for the person across from them. No allergies, no swaps.",
    category: "Food",
    spice: 6,
    minGroup: 2,
    maxGroup: 8,
    minTime: 60,
    maxTime: 120,
    venueQuery: ["restaurant"],
  },
  {
    id: "subway-portrait",
    title: "Public Transit Portrait Session",
    description:
      "On {city}'s transit, sketch the person sitting across from you (with consent). Trade sketches at the end.",
    category: "Creative",
    spice: 6,
    minGroup: 2,
    maxGroup: 6,
    minTime: 45,
    maxTime: 90,
  },
  {
    id: "bookstore-blind-date",
    title: "Bookstore Blind Date",
    description:
      "At a bookstore in {city}, each person picks a book for someone else based on vibes alone. Read aloud one page.",
    category: "Creative",
    spice: 2,
    minGroup: 2,
    maxGroup: 6,
    minTime: 45,
    maxTime: 90,
  },
  {
    id: "scavenger-five",
    title: "Five-Thing Scavenger",
    description:
      "In 60 minutes around {city}: find a feather, something purple, a free sticker, a stranger's recommendation, and a coin.",
    category: "Outdoor",
    spice: 3,
    minGroup: 2,
    maxGroup: 8,
    minTime: 60,
    maxTime: 75,
  },
  {
    id: "elevator-pitch",
    title: "Elevator Pitch Roulette",
    description:
      "Find a tall building lobby in {city}. Each person rides up with a stranger and pitches them a fake startup idea.",
    category: "Chaos",
    spice: 7,
    minGroup: 2,
    maxGroup: 5,
    minTime: 45,
    maxTime: 90,
  },
  {
    id: "dance-floor-import",
    title: "Dance Floor Import",
    description:
      "Find a place in {city} with music. Start a 30-second dance routine. See how many strangers join in.",
    category: "Chaos",
    spice: 7,
    minGroup: 3,
    maxGroup: 8,
    minTime: 30,
    maxTime: 90,
    lateNight: true,
  },
  {
    id: "free-museum-day",
    title: "Free Museum Speedrun",
    description:
      "Hit {venue} in {city} (or any free museum). Speedrun it in 20 minutes. Each person picks their favorite piece.",
    category: "Creative",
    spice: 2,
    minGroup: 1,
    maxGroup: 8,
    minTime: 30,
    maxTime: 60,
    venueQuery: ["museum"],
  },
  {
    id: "stranger-pic",
    title: "Stranger of the Day",
    description:
      "Approach one stranger in {city}. Ask their life story. Buy them a coffee. Post nothing.",
    category: "Social",
    spice: 5,
    minGroup: 1,
    maxGroup: 4,
    minTime: 30,
    maxTime: 60,
  },
  {
    id: "midnight-snack-quest",
    title: "Midnight Snack Quest",
    description:
      "After midnight, head to {venue} in {city} (or the strangest open food spot you can find). Order whatever the cashier recommends.",
    category: "Late Night",
    spice: 6,
    minGroup: 2,
    maxGroup: 6,
    minTime: 45,
    maxTime: 90,
    lateNight: true,
    venueQuery: ["fast_food", "restaurant"],
  },
  {
    id: "rooftop-recon",
    title: "Rooftop Recon",
    description:
      "Roll to {venue} in {city} (or any rooftop bar). Order the most colorful drink on the menu. Toast loudly.",
    category: "Social",
    spice: 4,
    minGroup: 2,
    maxGroup: 8,
    minTime: 60,
    maxTime: 120,
    venueQuery: ["bar"],
  },
  {
    id: "graffiti-tour",
    title: "Graffiti Self-Tour",
    description:
      "Walk a single mile in {city} photographing every piece of street art. Vote on the best at the end.",
    category: "Outdoor",
    spice: 2,
    minGroup: 1,
    maxGroup: 6,
    minTime: 45,
    maxTime: 90,
  },
  {
    id: "uber-roulette",
    title: "Rideshare Roulette",
    description:
      "Open a rideshare in {city}. Pick the third suggestion. Go there. Find dinner within 15 minutes of arrival.",
    category: "Chaos",
    spice: 6,
    minGroup: 2,
    maxGroup: 4,
    minTime: 90,
    maxTime: 180,
  },
  {
    id: "story-strangers",
    title: "Three Stories, Three Strangers",
    description:
      "Each person collects a 60-second story from a stranger in {city}. Retell them all at a bar later.",
    category: "Social",
    spice: 5,
    minGroup: 2,
    maxGroup: 6,
    minTime: 75,
    maxTime: 150,
  },
  {
    id: "vintage-photo",
    title: "Vintage Photo Recreation",
    description:
      "Find an old postcard of {city}. Recreate the photo with the group at the exact location.",
    category: "Creative",
    spice: 3,
    minGroup: 2,
    maxGroup: 8,
    minTime: 60,
    maxTime: 120,
  },
  {
    id: "improv-tour",
    title: "Improv Walking Tour",
    description:
      "One person leads a totally made-up historical tour of {city}. Every fact is a lie. Audience must keep a straight face.",
    category: "Creative",
    spice: 5,
    minGroup: 3,
    maxGroup: 8,
    minTime: 45,
    maxTime: 90,
  },
  {
    id: "wildcard-bartender",
    title: "Wildcard Bartender",
    description:
      "At {venue} in {city}, tell the bartender three adjectives. Drink whatever they make. No refusals.",
    category: "Late Night",
    spice: 7,
    minGroup: 2,
    maxGroup: 6,
    minTime: 45,
    maxTime: 90,
    lateNight: true,
    venueQuery: ["bar"],
  },
  {
    id: "park-picnic-blind",
    title: "Blind Picnic",
    description:
      "Each person brings one mystery snack to {venue} in {city}. Picnic-style, blind taste-test, rank them.",
    category: "Food",
    spice: 3,
    minGroup: 3,
    maxGroup: 8,
    minTime: 45,
    maxTime: 90,
    venueQuery: ["park"],
  },
  {
    id: "alphabet-walk",
    title: "Alphabet Walk",
    description:
      "Walk through {city} and photograph 26 things, one for each letter, in order. Time limit: 90 minutes.",
    category: "Outdoor",
    spice: 4,
    minGroup: 1,
    maxGroup: 6,
    minTime: 90,
    maxTime: 120,
  },
  {
    id: "stranger-dance",
    title: "Stranger Slow Dance",
    description:
      "At a bar or venue in {city} with music, politely ask one stranger for a 30-second dance. Group cheers them on.",
    category: "Chaos",
    spice: 9,
    minGroup: 3,
    maxGroup: 6,
    minTime: 60,
    maxTime: 120,
    lateNight: true,
  },
  {
    id: "best-pastry",
    title: "Best Pastry in {city}",
    description:
      "Visit 3 bakeries in {city}. One pastry each. Determine the winner by group vote and crown them with a paper crown.",
    category: "Food",
    spice: 2,
    minGroup: 2,
    maxGroup: 6,
    minTime: 90,
    maxTime: 150,
  },
  {
    id: "trash-treasure",
    title: "Trash to Treasure",
    description:
      "Find one piece of street trash in {city}. Turn it into art on the spot. Photograph and leave it for someone else.",
    category: "Creative",
    spice: 3,
    minGroup: 2,
    maxGroup: 6,
    minTime: 30,
    maxTime: 60,
  },
  {
    id: "playground-tag",
    title: "Adult Tag",
    description:
      "Meet at {venue} in {city}. Play one full round of tag. Wear whatever you're already wearing. No quitting.",
    category: "Outdoor",
    spice: 5,
    minGroup: 4,
    maxGroup: 10,
    minTime: 30,
    maxTime: 60,
    venueQuery: ["park", "playground"],
  },
  {
    id: "menu-translator",
    title: "Menu Translator",
    description:
      "Pick a restaurant in {city} with a menu in another language — try {venue}. No phones, order by pointing only.",
    category: "Food",
    spice: 5,
    minGroup: 2,
    maxGroup: 6,
    minTime: 60,
    maxTime: 90,
    venueQuery: ["restaurant"],
  },
  {
    id: "two-truths-locals",
    title: "Two Truths and a Local",
    description:
      "Each person collects one weird local fact from a stranger in {city}. Play two truths and a lie with them later.",
    category: "Social",
    spice: 4,
    minGroup: 3,
    maxGroup: 6,
    minTime: 60,
    maxTime: 120,
  },
  {
    id: "skate-or-roll",
    title: "Skate or Roll",
    description:
      "Rent skates, scooters, or bikes in {city}. Pick a destination 2 miles away. Race there. Loser gets coffee for the group.",
    category: "Outdoor",
    spice: 5,
    minGroup: 2,
    maxGroup: 6,
    minTime: 60,
    maxTime: 120,
  },
  {
    id: "stranger-selfie",
    title: "Stranger Selfie Roulette",
    description:
      "Politely ask 5 strangers in {city} for a group selfie. Collect them. Build a stranger photo album.",
    category: "Social",
    spice: 4,
    minGroup: 2,
    maxGroup: 8,
    minTime: 45,
    maxTime: 90,
  },
  {
    id: "candy-store-blind",
    title: "Candy Store Blindfold",
    description:
      "At a candy store in {city}, one person is blindfolded and picks $5 of candy by feel. Group eats it all.",
    category: "Food",
    spice: 4,
    minGroup: 2,
    maxGroup: 6,
    minTime: 30,
    maxTime: 60,
  },
  {
    id: "vinyl-hunt",
    title: "Vinyl Hunt",
    description:
      "Find a record store in {city}. Each person buys the album with the weirdest cover. Listen to a track each at home.",
    category: "Creative",
    spice: 3,
    minGroup: 2,
    maxGroup: 6,
    minTime: 60,
    maxTime: 90,
  },
  {
    id: "haunt-walk",
    title: "Self-Guided Haunt Walk",
    description:
      "After dark, walk through the oldest neighborhood in {city}. Each person invents a ghost story for one building.",
    category: "Late Night",
    spice: 4,
    minGroup: 2,
    maxGroup: 8,
    minTime: 60,
    maxTime: 120,
    lateNight: true,
  },
  {
    id: "movie-poster",
    title: "Movie Poster Group Pose",
    description:
      "Pick a famous movie poster. Recreate it in 3 different iconic spots around {city}. Best pose wins.",
    category: "Creative",
    spice: 4,
    minGroup: 3,
    maxGroup: 8,
    minTime: 60,
    maxTime: 120,
  },
  {
    id: "fortune-cookie-mission",
    title: "Fortune Cookie Mission",
    description:
      "Find a fortune cookie in {city}. Whatever it says, the group must do it (within reason) within the hour.",
    category: "Chaos",
    spice: 7,
    minGroup: 2,
    maxGroup: 6,
    minTime: 60,
    maxTime: 120,
  },
  {
    id: "best-bench",
    title: "Best Bench in {city}",
    description:
      "Start at {venue} in {city}. Find and rate 5 benches by view, comfort, and vibes. Award a sticky note to the winning bench.",
    venueQuery: ["park"],
    category: "Outdoor",
    spice: 1,
    minGroup: 1,
    maxGroup: 6,
    minTime: 60,
    maxTime: 120,
  },
  {
    id: "yes-day-mini",
    title: "Mini Yes-Day",
    description:
      "For the next 90 minutes in {city}, say yes to any reasonable suggestion from any group member.",
    category: "Chaos",
    spice: 8,
    minGroup: 2,
    maxGroup: 6,
    minTime: 90,
    maxTime: 180,
  },
  {
    id: "language-exchange",
    title: "Language Exchange Mission",
    description:
      "Find one stranger in {city} who speaks a language none of you do. Learn 3 words. Use them in your next order.",
    category: "Social",
    spice: 4,
    minGroup: 2,
    maxGroup: 5,
    minTime: 45,
    maxTime: 90,
  },
  {
    id: "secret-handshake",
    title: "Secret Handshake Genesis",
    description:
      "Invent a 6-step group handshake in {city}. Perform it at 3 different public spots. Get a stranger to learn it.",
    category: "Creative",
    spice: 4,
    minGroup: 3,
    maxGroup: 6,
    minTime: 45,
    maxTime: 90,
  },
  {
    id: "free-event-find",
    title: "Free Event Crash",
    description:
      "Find any free event happening in {city} tonight. Show up. Stay at least 30 minutes. Make one new friend.",
    category: "Social",
    spice: 5,
    minGroup: 1,
    maxGroup: 6,
    minTime: 90,
    maxTime: 180,
  },

  // ===== Chill =====
  { id: "silent-walk-5", title: "Silent 10-Minute Notice Walk", description: "Walk silently for 10 minutes in {city}. Each person notices 5 things they've never seen before. Compare lists.", category: "Chill", spice: 1, minGroup: 1, maxGroup: 6, minTime: 10, maxTime: 20, cost: "free" },
  { id: "cloud-shapes", title: "Cloud Shape Tribunal", description: "Lie on your back in a park in {city}. Each person names 3 cloud shapes. Vote on the most unhinged.", category: "Chill", spice: 1, minGroup: 1, maxGroup: 6, minTime: 15, maxTime: 30, cost: "free", venueQuery: ["park"] },
  { id: "library-hideout", title: "Library Hideout", description: "Find a quiet library corner in {city}. Read in silence for 30 minutes. Trade favorite sentences.", category: "Chill", spice: 1, minGroup: 1, maxGroup: 4, minTime: 30, maxTime: 60, cost: "free", venueQuery: ["library"] },
  { id: "coffee-letter", title: "Letter to Future You", description: "Sit at a cafe in {city}. Hand-write a letter to yourself one year from now. Seal it. Carry until then.", category: "Chill", spice: 1, minGroup: 1, maxGroup: 6, minTime: 30, maxTime: 60, cost: "$", venueQuery: ["cafe"] },
  { id: "ten-breath-bench", title: "Ten-Breath Bench", description: "Find the prettiest bench in {city}. Sit. Each person takes 10 slow breaths before speaking again.", category: "Chill", spice: 1, minGroup: 1, maxGroup: 5, minTime: 10, maxTime: 20, cost: "free" },
  { id: "no-phone-hour", title: "No-Phone Hour", description: "Lock phones away for one hour somewhere in {city}. Whoever checks first buys the next round of drinks.", category: "Chill", spice: 3, minGroup: 2, maxGroup: 8, minTime: 60, maxTime: 90, cost: "free" },
  { id: "favorite-songs", title: "Favorite-Song Swap", description: "At a quiet spot in {city}, each person plays one song that defines them this year. No skipping.", category: "Chill", spice: 2, minGroup: 2, maxGroup: 6, minTime: 30, maxTime: 60, cost: "free" },
  { id: "sunset-claim", title: "Sunset Claim", description: "Find the best free sunset view in {city}. Arrive 20 minutes early. Stay until full dark.", category: "Chill", spice: 1, minGroup: 1, maxGroup: 8, minTime: 45, maxTime: 90, cost: "free", venueQuery: ["viewpoint"] },
  { id: "playlist-trade", title: "Playlist Trade", description: "Make each other 5-track playlists on the spot from a cafe in {city}. Trade. Listen on the walk home.", category: "Chill", spice: 1, minGroup: 2, maxGroup: 4, minTime: 30, maxTime: 60, cost: "$", venueQuery: ["cafe"] },
  { id: "rainwatch", title: "Rainwatch", description: "If it's raining in {city}, find shelter with a view. Watch in silence for 20 minutes. Don't narrate.", category: "Chill", spice: 1, minGroup: 1, maxGroup: 4, minTime: 20, maxTime: 45, cost: "free" },
  { id: "porch-swap", title: "Porch Swap Notes", description: "Find a public seating area in {city}. Each person writes 3 anonymous compliments and leaves them on benches.", category: "Chill", spice: 2, minGroup: 2, maxGroup: 6, minTime: 30, maxTime: 60, cost: "free" },
  { id: "favorite-block", title: "Favorite Block Walk", description: "Each person picks their favorite block within walking distance of where you are in {city}. Tour all of them.", category: "Chill", spice: 1, minGroup: 2, maxGroup: 6, minTime: 60, maxTime: 120, cost: "free" },
  { id: "memory-recall-walk", title: "Memory-Recall Walk", description: "Walk through {city} and only talk about childhood memories. Whoever tells the funniest one buys coffee.", category: "Chill", spice: 2, minGroup: 2, maxGroup: 6, minTime: 30, maxTime: 60, cost: "$" },
  { id: "tea-ceremony", title: "DIY Tea Ceremony", description: "Hit a tea shop in {city}. Buy one tea each based purely on the name. Brew at someone's place.", category: "Chill", spice: 2, minGroup: 2, maxGroup: 6, minTime: 60, maxTime: 90, cost: "$" },
  { id: "puzzle-cafe", title: "Cafe Puzzle Race", description: "Bring or buy a 100-piece puzzle to a cafe in {city}. Race solo or in pairs. Winner picks the next quest.", category: "Chill", spice: 3, minGroup: 2, maxGroup: 6, minTime: 60, maxTime: 120, cost: "$", venueQuery: ["cafe"] },
  { id: "doodle-trade", title: "Doodle Trade", description: "On napkins at a cafe in {city}, doodle one thing for the person on your right. Sign and gift.", category: "Chill", spice: 1, minGroup: 2, maxGroup: 6, minTime: 30, maxTime: 60, cost: "$", venueQuery: ["cafe"] },
  { id: "gratitude-stones", title: "Gratitude Stone Drop", description: "Find 3 small stones outside in {city}. Write one gratitude on each in marker. Leave them on different benches.", category: "Chill", spice: 1, minGroup: 1, maxGroup: 6, minTime: 30, maxTime: 60, cost: "free" },
  { id: "horoscope-cafe", title: "Mutual Horoscope", description: "At a cafe in {city}, each person writes a fake horoscope for someone else in the group. Read aloud.", category: "Chill", spice: 2, minGroup: 3, maxGroup: 6, minTime: 30, maxTime: 60, cost: "$", venueQuery: ["cafe"] },

  // ===== Fitness =====
  { id: "stair-king", title: "Stair King", description: "Find the longest public staircase in {city}. Race to the top. Loser does 10 pushups at the bottom.", category: "Fitness", spice: 6, minGroup: 2, maxGroup: 6, minTime: 30, maxTime: 60, cost: "free" },
  { id: "5k-blitz", title: "Surprise 5K", description: "Pick a starting line in {city}. Run/walk 5K however slow. Crossing the finish, take a finisher pic.", category: "Fitness", spice: 5, minGroup: 1, maxGroup: 10, minTime: 30, maxTime: 90, cost: "free" },
  { id: "pull-up-park", title: "Pull-Up Park Tour", description: "Find 3 outdoor fitness setups in {city}. Each person does as many pull-ups as possible at each. Total wins.", category: "Fitness", spice: 5, minGroup: 2, maxGroup: 6, minTime: 60, maxTime: 90, cost: "free", venueQuery: ["park"] },
  { id: "yoga-anywhere", title: "Yoga Anywhere", description: "Do a 20-minute yoga flow in the weirdest legal spot in {city}. Photograph one pose at peak.", category: "Fitness", spice: 4, minGroup: 1, maxGroup: 8, minTime: 30, maxTime: 60, cost: "free" },
  { id: "bike-100min", title: "100-Minute Bike Tour", description: "Rent or bring bikes in {city}. Ride 100 minutes nonstop along the best route you can scout.", category: "Fitness", spice: 5, minGroup: 1, maxGroup: 6, minTime: 100, maxTime: 150, cost: "$$" },
  { id: "hike-up", title: "Hike Until You Can't", description: "Pick a trail or hill in {city}. Hike up until someone calls it. Take a peak photo.", category: "Fitness", spice: 6, minGroup: 1, maxGroup: 8, minTime: 90, maxTime: 240, cost: "free" },
  { id: "swim-find", title: "Find a Body of Water", description: "Locate any swimmable body of water near {city} (pool, lake, ocean). Dip in for at least 60 seconds.", category: "Fitness", spice: 6, minGroup: 2, maxGroup: 8, minTime: 90, maxTime: 240, cost: "$" },
  { id: "plank-bet", title: "Plank Bet", description: "Find a flat surface in {city}. Plank competition. Loser pays for everyone's next drink.", category: "Fitness", spice: 5, minGroup: 2, maxGroup: 6, minTime: 15, maxTime: 30, cost: "free" },
  { id: "stadium-stairs", title: "Stadium Stair Sprints", description: "Find a stadium or arena steps in {city}. Run up/down 10 times each. Last finisher buys recovery snacks.", category: "Fitness", spice: 7, minGroup: 2, maxGroup: 8, minTime: 45, maxTime: 90, cost: "free", venueQuery: ["stadium"] },
  { id: "dance-class-crash", title: "Dance Class Crash", description: "Find any drop-in dance class in {city}. Attend together. Most enthusiastic dancer wins glory.", category: "Fitness", spice: 6, minGroup: 2, maxGroup: 6, minTime: 60, maxTime: 120, cost: "$$" },
  { id: "boxing-shadow", title: "Shadow Boxing Round", description: "Find a public park in {city}. Each person does 3 minutes of shadow boxing while the others cheer.", category: "Fitness", spice: 5, minGroup: 2, maxGroup: 8, minTime: 20, maxTime: 45, cost: "free", venueQuery: ["park"] },
  { id: "sprint-corner", title: "Corner Sprint", description: "Pick a city block in {city}. Race to the corner. Best of three. No rematches.", category: "Fitness", spice: 5, minGroup: 2, maxGroup: 6, minTime: 10, maxTime: 20, cost: "free" },
  { id: "climbing-wall", title: "Bouldering First-Timer", description: "Find a climbing gym in {city}. Each person attempts 3 routes. Hardest send earns bragging rights.", category: "Fitness", spice: 5, minGroup: 1, maxGroup: 6, minTime: 90, maxTime: 180, cost: "$$", venueQuery: ["sports_centre"] },
  { id: "kickball-comeback", title: "Park Kickball", description: "Bring a ball to a park in {city}. Recruit 1 stranger to join. Play one inning.", category: "Fitness", spice: 6, minGroup: 4, maxGroup: 10, minTime: 60, maxTime: 90, cost: "$", venueQuery: ["park"] },
  { id: "morning-jog-cap", title: "5AM Jog Cap", description: "Meet at 5AM in {city}. Run/walk 30 minutes. Photograph the sunrise. Brunch follows.", category: "Fitness", spice: 7, minGroup: 2, maxGroup: 8, minTime: 60, maxTime: 120, cost: "$" },

  // ===== Nature =====
  { id: "oldest-tree", title: "Find the Oldest Tree", description: "Find what looks like the oldest tree near {city}. Estimate its age by trunk size. Photograph the group with it.", category: "Nature", spice: 2, minGroup: 1, maxGroup: 6, minTime: 60, maxTime: 120, cost: "free", venueQuery: ["park"] },
  { id: "bird-bingo", title: "Bird Bingo", description: "Make a bingo card of 9 likely birds in {city}. Spend 90 minutes spotting. First to bingo wins coffee.", category: "Nature", spice: 2, minGroup: 2, maxGroup: 6, minTime: 90, maxTime: 120, cost: "$", venueQuery: ["park"] },
  { id: "leaf-collection", title: "10 Leaves, 10 Stories", description: "Collect 10 distinct leaves in {city}. Invent a one-line backstory for each. Display on a bench.", category: "Nature", spice: 1, minGroup: 1, maxGroup: 6, minTime: 45, maxTime: 90, cost: "free", venueQuery: ["park"] },
  { id: "sunrise-spot", title: "Sunrise Hunt", description: "Find an east-facing public spot in {city}. Show up before dawn. Watch the sun clear the horizon.", category: "Nature", spice: 4, minGroup: 1, maxGroup: 8, minTime: 60, maxTime: 90, cost: "free" },
  { id: "moonwalk", title: "Full-Moon Moonwalk", description: "On the next full moon, walk for an hour in {city} with phones off. Each person shares one wish.", category: "Nature", spice: 3, minGroup: 2, maxGroup: 8, minTime: 60, maxTime: 90, cost: "free", lateNight: true },
  { id: "river-find", title: "Source of the Water", description: "Find any flowing water in {city}. Follow it as far as you can on foot. Take a group photo at the end.", category: "Nature", spice: 4, minGroup: 1, maxGroup: 6, minTime: 90, maxTime: 180, cost: "free" },
  { id: "stargaze", title: "Stargaze From the Best Dark Spot", description: "Find the darkest publicly accessible spot near {city}. Stay 30 minutes. Count shooting stars.", category: "Nature", spice: 3, minGroup: 1, maxGroup: 8, minTime: 60, maxTime: 120, cost: "free", lateNight: true, venueQuery: ["viewpoint"] },
  { id: "rock-skip", title: "Rock-Skipping Tournament", description: "Find any body of water in {city} with rocks. Each person gets 10 attempts. Most skips wins.", category: "Nature", spice: 2, minGroup: 2, maxGroup: 6, minTime: 30, maxTime: 60, cost: "free" },
  { id: "flower-snap", title: "Flower Snap Speedrun", description: "Photograph 15 different flowers/plants in {city} within 60 minutes. Identify with an app at the end.", category: "Nature", spice: 2, minGroup: 1, maxGroup: 4, minTime: 60, maxTime: 90, cost: "free" },
  { id: "barefoot-grass", title: "10 Minutes Barefoot", description: "Find clean grass in {city}. Take off shoes for 10 minutes. Each person names one childhood memory.", category: "Nature", spice: 2, minGroup: 1, maxGroup: 8, minTime: 10, maxTime: 30, cost: "free", venueQuery: ["park"] },
  { id: "tide-pool", title: "Tide Pool / Stream Survey", description: "Find a stream or shoreline in {city}. Count distinct living things you can see in 20 minutes.", category: "Nature", spice: 3, minGroup: 1, maxGroup: 6, minTime: 45, maxTime: 90, cost: "free" },
  { id: "wildlife-watch", title: "Wildlife Watch", description: "Sit very still at a green space in {city} for 30 minutes. Photograph the most interesting living thing.", category: "Nature", spice: 2, minGroup: 1, maxGroup: 4, minTime: 30, maxTime: 60, cost: "free", venueQuery: ["park"] },
  { id: "compost-mission", title: "Compost Mission", description: "Find a community garden or composting site in {city}. Volunteer for an hour. Take a dirt selfie.", category: "Nature", spice: 3, minGroup: 1, maxGroup: 6, minTime: 60, maxTime: 120, cost: "free" },
  { id: "trash-cleanup", title: "Mini Cleanup", description: "Bring gloves and a bag. Pick up trash on one block in {city} for 30 minutes. Photograph the haul.", category: "Nature", spice: 3, minGroup: 1, maxGroup: 8, minTime: 30, maxTime: 60, cost: "free" },
  { id: "cloud-photo", title: "Best Cloud Photo", description: "60 minutes in {city}. Each person captures one cloud photo. Group votes on the absolute best.", category: "Nature", spice: 1, minGroup: 2, maxGroup: 8, minTime: 60, maxTime: 90, cost: "free" },

  // ===== Tech =====
  { id: "ai-portrait", title: "AI Portrait Hunt", description: "In {city}, each person finds something IRL that matches an AI-generated image you all agree on. First to match wins.", category: "Tech", spice: 5, minGroup: 2, maxGroup: 6, minTime: 60, maxTime: 120, cost: "free" },
  { id: "qr-treasure", title: "QR Treasure", description: "One person hides 5 QR codes around {city} pointing to absurd memes. Everyone else hunts and screenshots.", category: "Tech", spice: 6, minGroup: 3, maxGroup: 8, minTime: 90, maxTime: 150, cost: "free" },
  { id: "ai-restaurant", title: "AI-Picked Restaurant", description: "Ask any AI to pick a restaurant in {city}. Go. Follow its ordering recommendation exactly.", category: "Tech", spice: 5, minGroup: 2, maxGroup: 6, minTime: 60, maxTime: 120, cost: "$$", venueQuery: ["restaurant"] },
  { id: "geocache", title: "Geocache Hunt", description: "Open a geocaching app. Find at least one cache within {city}. Sign the log if you find it.", category: "Tech", spice: 4, minGroup: 1, maxGroup: 6, minTime: 60, maxTime: 120, cost: "free" },
  { id: "google-street-flashback", title: "Street View Flashback", description: "Pick a Google Street View spot from 10+ years ago in {city}. Visit it IRL. Recreate the screenshot.", category: "Tech", spice: 3, minGroup: 1, maxGroup: 6, minTime: 60, maxTime: 120, cost: "free" },
  { id: "yelp-bottom", title: "Yelp Bottom-Rated", description: "Find the lowest-rated open restaurant in {city} on Yelp. Order one item. Decide if the rating is fair.", category: "Tech", spice: 7, minGroup: 2, maxGroup: 5, minTime: 60, maxTime: 90, cost: "$", venueQuery: ["restaurant", "fast_food"] },
  { id: "ai-name-quest", title: "AI Names the Quest", description: "Ask an AI to generate a quest 'in {city} for {groupSize} people'. Do whatever it says (within reason).", category: "Tech", spice: 7, minGroup: 2, maxGroup: 6, minTime: 60, maxTime: 180, cost: "$" },
  { id: "drone-photo", title: "Drone-Style Group Shot", description: "Find the highest legal vantage in {city}. Get a top-down group photo. Bonus: actual drone if allowed.", category: "Tech", spice: 4, minGroup: 2, maxGroup: 10, minTime: 60, maxTime: 120, cost: "free", venueQuery: ["viewpoint"] },
  { id: "wikipedia-roulette", title: "Wikipedia Roulette", description: "Hit Wikipedia's Random Article 3 times. Pick the one with the closest {city} tie-in. Visit a related place.", category: "Tech", spice: 4, minGroup: 1, maxGroup: 6, minTime: 60, maxTime: 120, cost: "free" },
  { id: "smart-home-demo", title: "Smart Home Demo Crash", description: "Walk into any electronics store in {city}. Have a 5-minute tour by an employee. Buy nothing.", category: "Tech", spice: 5, minGroup: 1, maxGroup: 4, minTime: 30, maxTime: 60, cost: "free" },
  { id: "podcast-record", title: "10-Min Podcast Record", description: "Find an interesting bench in {city}. Record a 10-minute podcast about what you see. Publish or delete.", category: "Tech", spice: 4, minGroup: 2, maxGroup: 4, minTime: 30, maxTime: 60, cost: "free" },
  { id: "ai-photo-prompt", title: "Reverse Photo Prompt", description: "Take one weird photo in {city}. Ask AI to caption it. Group picks the funniest caption.", category: "Tech", spice: 3, minGroup: 2, maxGroup: 6, minTime: 30, maxTime: 45, cost: "free" },

  // ===== Exploration =====
  { id: "unknown-neighborhood", title: "Unknown Neighborhood Drop", description: "Pick a neighborhood in {city} none of you has ever set foot in. Spend 90 minutes exploring it on foot.", category: "Exploration", spice: 4, minGroup: 1, maxGroup: 6, minTime: 90, maxTime: 150, cost: "$" },
  { id: "every-floor", title: "Every Floor of a Tall Building", description: "Find a public-access tall building in {city}. Visit every floor with public access. Take a photo on each.", category: "Exploration", spice: 5, minGroup: 1, maxGroup: 4, minTime: 60, maxTime: 120, cost: "free" },
  { id: "abandoned-near", title: "Abandoned-Looking Spot (Legal)", description: "Find the most abandoned-looking but legally accessible spot in {city}. Photograph it like a movie poster.", category: "Exploration", spice: 6, minGroup: 2, maxGroup: 6, minTime: 90, maxTime: 180, cost: "free" },
  { id: "30-block-mile", title: "30-Block Mile", description: "Pick a starting point in {city}. Walk a full mile. Stop at the 30th most interesting thing you see.", category: "Exploration", spice: 3, minGroup: 1, maxGroup: 6, minTime: 60, maxTime: 90, cost: "free" },
  { id: "every-train", title: "Every Train Line, One Stop", description: "Ride every available train/bus line in {city} for exactly one stop. Document the line names.", category: "Exploration", spice: 6, minGroup: 1, maxGroup: 4, minTime: 120, maxTime: 240, cost: "$" },
  { id: "alleyway-tour", title: "Alleyway Tour", description: "Walk only down alleys in {city} for 45 minutes (where legal/safe). Photograph the strangest thing you see.", category: "Exploration", spice: 5, minGroup: 2, maxGroup: 4, minTime: 45, maxTime: 90, cost: "free" },
  { id: "highest-public-place", title: "Highest Public Point", description: "Find the highest publicly accessible point in {city}. Read aloud the first sentence of a novel at the top.", category: "Exploration", spice: 4, minGroup: 1, maxGroup: 8, minTime: 60, maxTime: 120, cost: "free", venueQuery: ["viewpoint"] },
  { id: "lowest-public-place", title: "Lowest Public Point", description: "Find the lowest publicly accessible place in {city} (basement, underpass, subway). Sit for 5 minutes.", category: "Exploration", spice: 4, minGroup: 2, maxGroup: 6, minTime: 30, maxTime: 60, cost: "free" },
  { id: "follow-stranger-loose", title: "Loose Follow", description: "From a safe distance, walk in the same direction as a random stranger in {city} for 5 minutes. Don't be creepy.", category: "Exploration", spice: 5, minGroup: 2, maxGroup: 4, minTime: 15, maxTime: 30, cost: "free" },
  { id: "neighborhood-mascot", title: "Neighborhood Mascot Hunt", description: "Pick a neighborhood in {city}. Find or invent its 'mascot' (an animal, statue, sign, person). Photograph proof.", category: "Exploration", spice: 3, minGroup: 2, maxGroup: 6, minTime: 60, maxTime: 90, cost: "free" },
  { id: "compass-walk", title: "Compass Walk North", description: "Open a compass. Walk due north from your current spot in {city} for 30 minutes. Re-route only when blocked.", category: "Exploration", spice: 5, minGroup: 1, maxGroup: 4, minTime: 45, maxTime: 90, cost: "free" },
  { id: "transit-roulette", title: "Transit Roulette", description: "Take the next bus/train leaving {city}'s nearest stop. Get off at the 5th stop. Find dinner within a 10-minute walk.", category: "Exploration", spice: 7, minGroup: 1, maxGroup: 6, minTime: 90, maxTime: 180, cost: "$$" },
  { id: "find-the-fountain", title: "Find Every Fountain", description: "Find every public fountain within walking distance in {city}. Photograph each. Coin toss in the best one.", category: "Exploration", spice: 3, minGroup: 1, maxGroup: 6, minTime: 60, maxTime: 120, cost: "$" },
  { id: "library-floor-scan", title: "Library Floor Scan", description: "Walk every floor of the largest library in {city}. Bring back one weird book each.", category: "Exploration", spice: 2, minGroup: 1, maxGroup: 4, minTime: 60, maxTime: 90, cost: "free", venueQuery: ["library"] },
  { id: "free-tour-crash", title: "Free Walking Tour Crash", description: "Find or improvise a free walking tour in {city}. Tag along or run one yourselves for tourists.", category: "Exploration", spice: 5, minGroup: 2, maxGroup: 6, minTime: 90, maxTime: 180, cost: "free" },
  { id: "smell-map", title: "Smell Map of the City", description: "Walk 1 mile in {city}. Each person logs 10 distinct smells with locations. Compile a smell map.", category: "Exploration", spice: 3, minGroup: 1, maxGroup: 4, minTime: 60, maxTime: 90, cost: "free" },
  { id: "sound-walk", title: "Sound Walk", description: "Walk 30 minutes in {city} with earbuds out. Identify 20 distinct sounds. Most accurate list wins.", category: "Exploration", spice: 2, minGroup: 1, maxGroup: 6, minTime: 30, maxTime: 60, cost: "free" },
  { id: "lost-on-purpose", title: "Lost on Purpose", description: "In {city}, turn off GPS. Walk 30 minutes without a destination. Find your way home using only people.", category: "Exploration", spice: 7, minGroup: 2, maxGroup: 4, minTime: 60, maxTime: 120, cost: "free" },

  // ===== Chaos (additional) =====
  { id: "rps-stranger", title: "Stranger Rock Paper Scissors", description: "Politely challenge 5 strangers in {city} to rock paper scissors. Best of one. Tally a winning streak.", category: "Chaos", spice: 6, minGroup: 1, maxGroup: 4, minTime: 30, maxTime: 60, cost: "free" },
  { id: "high-five-50", title: "50 High-Fives", description: "Get 50 high-fives from strangers in {city} within 60 minutes. Group split-counts allowed.", category: "Chaos", spice: 7, minGroup: 2, maxGroup: 8, minTime: 60, maxTime: 90, cost: "free" },
  { id: "elevator-song", title: "Elevator Song", description: "Find a public elevator in {city}. Sing one full chorus of a song before reaching your floor. No quitting.", category: "Chaos", spice: 9, minGroup: 2, maxGroup: 4, minTime: 15, maxTime: 30, cost: "free" },
  { id: "lost-tourist", title: "Worst Tour Guide", description: "In {city}, recruit one real tourist. Give them deliberately wrong but harmless directions to a fun place.", category: "Chaos", spice: 7, minGroup: 2, maxGroup: 4, minTime: 30, maxTime: 60, cost: "free" },
  { id: "compliment-loud", title: "Loud Compliment Loop", description: "In a public square in {city}, loudly compliment 3 strangers each in a way they can't miss. No phones.", category: "Chaos", spice: 8, minGroup: 2, maxGroup: 6, minTime: 30, maxTime: 60, cost: "free" },
  { id: "free-fortune", title: "Sidewalk Fortune Teller", description: "One person sets up as a free fortune teller in {city}. Group recruits 5 willing strangers in 60 minutes.", category: "Chaos", spice: 8, minGroup: 3, maxGroup: 6, minTime: 60, maxTime: 120, cost: "free" },
  { id: "swap-shoes", title: "Swap Shoes for 20 Minutes", description: "Pair up. Swap one shoe each. Walk 20 minutes in {city}. Don't say why if asked.", category: "Chaos", spice: 6, minGroup: 2, maxGroup: 6, minTime: 20, maxTime: 45, cost: "free" },
  { id: "balloon-deliver", title: "Random Balloon Delivery", description: "Buy a single balloon in {city}. Gift it to a stranger with a tiny compliment. Document the reaction (with consent).", category: "Chaos", spice: 7, minGroup: 2, maxGroup: 4, minTime: 45, maxTime: 90, cost: "$" },
  { id: "name-change", title: "Fake Names Mission", description: "Pick a fake name each for the next 60 minutes in {city}. Use them at every order. Don't break.", category: "Chaos", spice: 6, minGroup: 2, maxGroup: 6, minTime: 60, maxTime: 90, cost: "$" },
  { id: "synchronized-walk", title: "Synchronized Walk", description: "Walk through {city} in perfect lockstep for 5 minutes. Photograph yourselves doing it in 3 spots.", category: "Chaos", spice: 5, minGroup: 3, maxGroup: 6, minTime: 30, maxTime: 60, cost: "free" },
  { id: "shout-poetry", title: "Shouted Poetry", description: "Stand on a public bench in {city}. Each person shouts one line of original poetry. Bow. Walk away.", category: "Chaos", spice: 9, minGroup: 2, maxGroup: 6, minTime: 15, maxTime: 30, cost: "free" },
  { id: "tiny-parade", title: "Tiny Parade", description: "Pick a theme. March in formation for 10 minutes through {city}. Group photo afterward.", category: "Chaos", spice: 8, minGroup: 3, maxGroup: 10, minTime: 30, maxTime: 60, cost: "free" },

  // ===== Outdoor (additional) =====
  { id: "puddle-jump", title: "Puddle Jump Bracket", description: "After rain in {city}, find 5 puddles. Each person jumps each. Splash photos. Group votes on style.", category: "Outdoor", spice: 4, minGroup: 2, maxGroup: 6, minTime: 30, maxTime: 60, cost: "free" },
  { id: "snow-tag", title: "First Snow Tag", description: "If there's snow in {city}, play 10 minutes of tag. Loser does a snow angel.", category: "Outdoor", spice: 5, minGroup: 3, maxGroup: 8, minTime: 30, maxTime: 60, cost: "free" },
  { id: "outdoor-photoshoot", title: "Outdoor Photoshoot", description: "Pick a magazine cover style. Recreate it outdoors in {city} with phone cameras. Best edit wins.", category: "Outdoor", spice: 5, minGroup: 2, maxGroup: 6, minTime: 60, maxTime: 120, cost: "free" },
  { id: "kite-fly", title: "Kite or Frisbee", description: "Buy or bring a kite/frisbee. Find an open space in {city}. Spend 60 minutes losing track of time.", category: "Outdoor", spice: 3, minGroup: 2, maxGroup: 8, minTime: 60, maxTime: 90, cost: "$", venueQuery: ["park"] },
  { id: "spotlight-monument", title: "Statue Roast", description: "Find a public statue in {city}. Each person delivers a 30-second roast of the subject. Funniest wins.", category: "Outdoor", spice: 6, minGroup: 3, maxGroup: 6, minTime: 30, maxTime: 60, cost: "free" },
  { id: "free-paper", title: "Free-Newspaper Crawl", description: "Collect one free publication from 5 different places in {city}. Read aloud the weirdest line at the end.", category: "Outdoor", spice: 3, minGroup: 1, maxGroup: 4, minTime: 60, maxTime: 90, cost: "free" },
  { id: "shadow-race", title: "Shadow Race", description: "On a sunny day in {city}, race only by stepping on shadows. First to a chosen landmark wins.", category: "Outdoor", spice: 4, minGroup: 2, maxGroup: 6, minTime: 30, maxTime: 60, cost: "free" },
  { id: "open-air-market", title: "Open-Air Market Hunt", description: "Find an outdoor market in {city}. Each person buys the strangest $5 thing. Compare at a bench.", category: "Outdoor", spice: 4, minGroup: 2, maxGroup: 6, minTime: 90, maxTime: 120, cost: "$$" },
  { id: "outdoor-trivia", title: "Outdoor Trivia Walk", description: "Walk through {city}. One person quizzes the others on landmarks they see. 10 questions. Most right wins.", category: "Outdoor", spice: 3, minGroup: 2, maxGroup: 6, minTime: 60, maxTime: 90, cost: "free" },
  { id: "city-hike", title: "Urban Hike 5 Miles", description: "Walk 5 miles through {city} without taking the same street twice. Track on a map.", category: "Outdoor", spice: 5, minGroup: 1, maxGroup: 6, minTime: 120, maxTime: 240, cost: "free" },
  { id: "stargaze-roof", title: "Rooftop Stargaze (Legal)", description: "Find a publicly accessible rooftop or hill in {city}. Stay until you see 10 stars. Make a wish each.", category: "Outdoor", spice: 4, minGroup: 2, maxGroup: 6, minTime: 60, maxTime: 120, cost: "free", lateNight: true },
  { id: "morning-coffee-walk", title: "Walking Coffee", description: "Buy coffee in {city}. Walk and sip for 30 minutes only. Each person shares one tiny goal for the day.", category: "Outdoor", spice: 1, minGroup: 1, maxGroup: 6, minTime: 30, maxTime: 45, cost: "$", venueQuery: ["cafe"] },

  // ===== Social (additional) =====
  { id: "ten-questions-stranger", title: "10 Questions, 1 Stranger", description: "Politely ask one stranger in {city} 10 questions about their life. Buy them a coffee. Don't get on their socials.", category: "Social", spice: 6, minGroup: 1, maxGroup: 3, minTime: 45, maxTime: 90, cost: "$" },
  { id: "compliment-shuffle", title: "Stranger Compliment Shuffle", description: "Each person finds a stranger in {city} to give a unique 1-sentence compliment. Document polite reactions.", category: "Social", spice: 5, minGroup: 2, maxGroup: 6, minTime: 30, maxTime: 60, cost: "free" },
  { id: "block-party-find", title: "Find a Block Party", description: "Hunt down any block party, market, or street fair in {city}. Stay 30 minutes. Make one new friend.", category: "Social", spice: 5, minGroup: 1, maxGroup: 6, minTime: 90, maxTime: 180, cost: "$" },
  { id: "trivia-pop", title: "Pop into Trivia Night", description: "Find a bar with trivia tonight in {city}. Join as a team. Honest goal: don't finish last.", category: "Social", spice: 5, minGroup: 2, maxGroup: 6, minTime: 90, maxTime: 180, cost: "$$", lateNight: true, venueQuery: ["bar"] },
  { id: "speed-friend", title: "Speed Friending", description: "Pair up at a cafe in {city}. 5 minutes per pair, 5 rotations. Each person rates the chats privately.", category: "Social", spice: 4, minGroup: 4, maxGroup: 8, minTime: 60, maxTime: 90, cost: "$", venueQuery: ["cafe"] },
  { id: "language-cafe", title: "Language Cafe Drop-In", description: "Find a language exchange meetup in {city}. Show up. Have a 5-minute chat in any language you barely know.", category: "Social", spice: 5, minGroup: 1, maxGroup: 4, minTime: 90, maxTime: 150, cost: "free" },
  { id: "letter-deliver", title: "Letter Drop", description: "Each person hand-writes a letter to a friend not in the group. Mail them together from a {city} post office.", category: "Social", spice: 2, minGroup: 2, maxGroup: 6, minTime: 60, maxTime: 90, cost: "$" },
  { id: "phone-swap", title: "Phone Swap Hour", description: "For one hour in {city}, swap phones with the person on your left. Only respond if they would.", category: "Social", spice: 8, minGroup: 2, maxGroup: 6, minTime: 60, maxTime: 90, cost: "free" },
  { id: "open-mic-watch", title: "Open Mic Witness", description: "Find an open mic in {city}. Stay for 5 acts. Each person picks one favorite and tells the performer.", category: "Social", spice: 5, minGroup: 2, maxGroup: 6, minTime: 90, maxTime: 180, cost: "$$", lateNight: true },
  { id: "small-favor", title: "Small Favor Mission", description: "Do one small unsolicited favor for a stranger in {city} (carry bags, give directions). Three each.", category: "Social", spice: 4, minGroup: 2, maxGroup: 6, minTime: 45, maxTime: 90, cost: "free" },
  { id: "two-truths-bus", title: "Two Truths and a Bus Ride", description: "On a bus/train in {city}, quietly play two truths and a lie. Get one stranger to overhear and guess.", category: "Social", spice: 6, minGroup: 2, maxGroup: 4, minTime: 45, maxTime: 90, cost: "$" },
  { id: "park-game-recruit", title: "Park Game Recruit", description: "Bring a card or board game to a park in {city}. Recruit at least 2 strangers to join. Play one full round.", category: "Social", spice: 6, minGroup: 2, maxGroup: 4, minTime: 60, maxTime: 120, cost: "free", venueQuery: ["park"] },
  { id: "secret-confidant", title: "Secret Confidant Walk", description: "Walk through {city} in pairs. Each person shares one thing they've never told anyone. Vault rule.", category: "Social", spice: 7, minGroup: 4, maxGroup: 6, minTime: 60, maxTime: 90, cost: "free" },
  { id: "5-strangers-question", title: "5 Strangers, 1 Question", description: "Pick one question. Ask 5 strangers in {city}. Average their answers. Compare to your own.", category: "Social", spice: 5, minGroup: 1, maxGroup: 4, minTime: 45, maxTime: 90, cost: "free" },

  // ===== Creative (additional) =====
  { id: "haiku-spot", title: "Haiku Each Spot", description: "Pick 5 spots in {city}. Each person writes a haiku for each. Read them aloud at the last spot.", category: "Creative", spice: 3, minGroup: 1, maxGroup: 6, minTime: 60, maxTime: 120, cost: "free" },
  { id: "music-video-shoot", title: "1-Take Music Video", description: "Pick a 90-second song. Choreograph and shoot a one-take video in {city}. Share with the group.", category: "Creative", spice: 6, minGroup: 2, maxGroup: 6, minTime: 60, maxTime: 90, cost: "free" },
  { id: "improvise-name", title: "Storefront Story", description: "Pick a random storefront in {city}. Invent a 60-second backstory for the owner. Funniest wins.", category: "Creative", spice: 3, minGroup: 2, maxGroup: 6, minTime: 30, maxTime: 60, cost: "free" },
  { id: "flash-fiction", title: "Flash Fiction at the Park", description: "Sit in a park in {city}. Write a 200-word story inspired by one person you see. Read aloud.", category: "Creative", spice: 3, minGroup: 1, maxGroup: 6, minTime: 45, maxTime: 75, cost: "free", venueQuery: ["park"] },
  { id: "diy-zine", title: "DIY Zine in 90 Minutes", description: "Buy a single sheet of paper. Make a folded zine about {city}. Trade with another group member.", category: "Creative", spice: 3, minGroup: 2, maxGroup: 6, minTime: 90, maxTime: 120, cost: "$" },
  { id: "soundtrack-walk", title: "Personal Soundtrack Walk", description: "Each person picks one album. Walk together in {city}. After every track, swap to the next person's album.", category: "Creative", spice: 2, minGroup: 2, maxGroup: 6, minTime: 60, maxTime: 120, cost: "free" },
  { id: "perfume-blind", title: "Perfume Blind Test", description: "Visit a department store in {city}. Sniff 10 perfumes blind. Each person names what each reminds them of.", category: "Creative", spice: 3, minGroup: 2, maxGroup: 6, minTime: 45, maxTime: 75, cost: "free" },
  { id: "5-photo-essay", title: "5-Photo Photo Essay", description: "Walk through {city}. Build a 5-photo essay on one tiny theme. Present like an art critic.", category: "Creative", spice: 3, minGroup: 1, maxGroup: 6, minTime: 60, maxTime: 90, cost: "free" },
  { id: "chalk-art", title: "Sidewalk Chalk Mural", description: "Buy chalk. Find legal sidewalk space in {city}. Group mural in 30 minutes. Photograph and walk away.", category: "Creative", spice: 4, minGroup: 2, maxGroup: 8, minTime: 45, maxTime: 90, cost: "$" },
  { id: "poetry-postcards", title: "Poetry Postcards", description: "Each person buys a postcard in {city}, writes an original poem on the back, and mails it to a stranger's address from a phone book.", category: "Creative", spice: 5, minGroup: 2, maxGroup: 6, minTime: 60, maxTime: 90, cost: "$" },
  { id: "art-fake-tour", title: "Fake Gallery Tour", description: "Walk through a free gallery in {city}. One person explains every piece as if they painted it. Stay 30 minutes.", category: "Creative", spice: 7, minGroup: 2, maxGroup: 6, minTime: 45, maxTime: 90, cost: "free", venueQuery: ["museum"] },
  { id: "alphabet-photo", title: "Alphabet Photo Quest", description: "Photograph 26 things in {city}, one per letter, in alphabetical order. 90-minute limit.", category: "Creative", spice: 4, minGroup: 1, maxGroup: 6, minTime: 90, maxTime: 120, cost: "free" },
  { id: "sketch-stranger", title: "Sketch a Stranger (Consent)", description: "Politely ask 3 strangers in {city} for permission to sketch them in 2 minutes. Gift them the sketch.", category: "Creative", spice: 5, minGroup: 2, maxGroup: 6, minTime: 45, maxTime: 75, cost: "$" },
  { id: "remix-song", title: "Remix a Song with Sounds", description: "Walk 30 minutes in {city}. Record sounds. Cut a 60-second remix of any song using only those sounds.", category: "Creative", spice: 4, minGroup: 1, maxGroup: 4, minTime: 60, maxTime: 120, cost: "free" },

  // ===== Food (additional) =====
  { id: "cant-read-menu", title: "Can't-Read-the-Menu Dinner", description: "Eat at a restaurant in {city} where you cannot read the menu. Order by guessing. No translations.", category: "Food", spice: 6, minGroup: 2, maxGroup: 6, minTime: 60, maxTime: 120, cost: "$$", venueQuery: ["restaurant"] },
  { id: "$5-dinner", title: "$5 Dinner Challenge", description: "Build a full dinner for the group on $5 each from any {city} grocery. Eat at a park.", category: "Food", spice: 4, minGroup: 2, maxGroup: 6, minTime: 60, maxTime: 120, cost: "$", venueQuery: ["supermarket"] },
  { id: "single-ingredient", title: "Single-Ingredient Sprint", description: "Pick one weird ingredient (e.g. cilantro). Build a 3-course meal using it in every dish from {city} stores.", category: "Food", spice: 5, minGroup: 2, maxGroup: 6, minTime: 120, maxTime: 180, cost: "$$" },
  { id: "blindfold-taste", title: "Blindfold Taste Test", description: "Buy 5 random snacks in {city}. Blindfold each person and taste. Most correct guesses wins.", category: "Food", spice: 4, minGroup: 2, maxGroup: 6, minTime: 30, maxTime: 60, cost: "$" },
  { id: "cuisine-roulette", title: "Cuisine Roulette", description: "Spin for a random cuisine. Find the best version in {city}. Order the most adventurous thing.", category: "Food", spice: 5, minGroup: 2, maxGroup: 6, minTime: 90, maxTime: 150, cost: "$$", venueQuery: ["restaurant"] },
  { id: "dessert-first", title: "Dessert First Tour", description: "Eat only dessert for one meal across 3 spots in {city}. Score each. Best wins a paper crown.", category: "Food", spice: 3, minGroup: 2, maxGroup: 6, minTime: 90, maxTime: 150, cost: "$$" },
  { id: "5-bites", title: "5 Bites, 5 Cuisines", description: "Five fast bites, five cuisines, one hour in {city}. Smallest plate at each. Photograph each bite.", category: "Food", spice: 5, minGroup: 2, maxGroup: 6, minTime: 60, maxTime: 90, cost: "$$" },
  { id: "weirdest-flavor", title: "Weirdest Flavor Hunt", description: "Find the weirdest flavor combo on sale in {city}. Each person tries one bite. Vote on best/worst.", category: "Food", spice: 5, minGroup: 2, maxGroup: 6, minTime: 60, maxTime: 90, cost: "$" },
  { id: "happy-hour-tour", title: "Happy Hour Tour", description: "Hit 3 happy hours in {city}. One small plate each. Rank value-for-money.", category: "Food", spice: 5, minGroup: 2, maxGroup: 6, minTime: 120, maxTime: 180, cost: "$$$", lateNight: true, venueQuery: ["bar"] },
  { id: "cafeteria-mystery", title: "Cafeteria Mystery", description: "Find any cafeteria/canteen in {city}. Get a tray. Try every item, even the ones you don't recognize.", category: "Food", spice: 4, minGroup: 2, maxGroup: 6, minTime: 60, maxTime: 90, cost: "$" },
  { id: "first-thing-special", title: "First Special of the Day", description: "Pick a restaurant in {city}. Order the first special on the menu, no questions. Eat it all.", category: "Food", spice: 5, minGroup: 1, maxGroup: 6, minTime: 60, maxTime: 90, cost: "$$", venueQuery: ["restaurant"] },
  { id: "tasting-flight", title: "Tasting Flight Tour", description: "Find any tasting flight in {city} (coffee, beer, tea). Order. Rank from worst to best honestly.", category: "Food", spice: 4, minGroup: 2, maxGroup: 6, minTime: 60, maxTime: 120, cost: "$$" },
  { id: "five-truffles", title: "Top-Shelf Chocolate Five", description: "Find a fancy chocolate shop in {city}. Each person picks one $5 truffle. Blind-taste and rank.", category: "Food", spice: 2, minGroup: 2, maxGroup: 6, minTime: 30, maxTime: 60, cost: "$$" },
  { id: "every-pickle", title: "Every Pickle in the Aisle", description: "Find a grocery in {city}. Buy 3 pickle varieties. Group blind taste at a park.", category: "Food", spice: 3, minGroup: 2, maxGroup: 6, minTime: 45, maxTime: 75, cost: "$", venueQuery: ["supermarket"] },

  // ===== Late Night (additional) =====
  { id: "midnight-photo-walk", title: "Midnight Photo Walk", description: "Walk through {city} from midnight to 1am. Each person takes 5 long-exposure photos. Best gets framed.", category: "Late Night", spice: 5, minGroup: 1, maxGroup: 6, minTime: 60, maxTime: 90, cost: "free", lateNight: true },
  { id: "all-night-diner", title: "Pancakes at 3AM", description: "Find a 24-hour spot in {city}. Order only pancakes. Each person picks a topic to debate until sunrise.", category: "Late Night", spice: 6, minGroup: 2, maxGroup: 6, minTime: 90, maxTime: 180, cost: "$$", lateNight: true, venueQuery: ["restaurant"] },
  { id: "neon-tour", title: "Neon Sign Hunt", description: "After dark in {city}, photograph 10 neon signs. Vote on the most iconic. Eat at a place under it.", category: "Late Night", spice: 4, minGroup: 1, maxGroup: 6, minTime: 90, maxTime: 150, cost: "$$", lateNight: true },
  { id: "ghost-story-circle", title: "Ghost Story Circle", description: "At midnight in {city}, find a quiet bench. Each person tells one ghost story. Most original wins.", category: "Late Night", spice: 4, minGroup: 3, maxGroup: 6, minTime: 60, maxTime: 90, cost: "free", lateNight: true },
  { id: "after-dark-bookstore", title: "After-Dark Bookstore", description: "Find a late-open bookstore in {city}. Each person picks a book by cover alone. Read 10 pages aloud.", category: "Late Night", spice: 3, minGroup: 2, maxGroup: 6, minTime: 60, maxTime: 90, cost: "$$", lateNight: true },
  { id: "secret-bar", title: "Speakeasy Recon", description: "Hunt down any hidden/speakeasy-style bar in {city}. Order the bartender's choice. Tip well.", category: "Late Night", spice: 6, minGroup: 2, maxGroup: 4, minTime: 90, maxTime: 150, cost: "$$$", lateNight: true, venueQuery: ["bar"] },
  { id: "late-grocery-snack", title: "Midnight Grocery Snack Run", description: "Hit any open grocery in {city} after 11pm. $7 each on impulse buys. Reconvene and rank.", category: "Late Night", spice: 4, minGroup: 2, maxGroup: 6, minTime: 30, maxTime: 60, cost: "$", lateNight: true, venueQuery: ["supermarket"] },
  { id: "moon-cinema", title: "Moonlit Cinema", description: "Stream a 30-minute short on a phone or laptop on a rooftop or open space in {city} after midnight.", category: "Late Night", spice: 4, minGroup: 2, maxGroup: 6, minTime: 60, maxTime: 90, cost: "free", lateNight: true },
  { id: "dawn-pancakes", title: "Pre-Dawn Coffee Run", description: "Be at a 24-hour coffee shop in {city} by 4:30am. Order. Watch the city wake up.", category: "Late Night", spice: 6, minGroup: 1, maxGroup: 6, minTime: 60, maxTime: 90, cost: "$", lateNight: true, venueQuery: ["cafe"] },
  { id: "karaoke-bar-roll", title: "Karaoke Bar Roll", description: "Find a karaoke spot in {city}. Each person sings one song chosen by the group. No rejecting picks.", category: "Late Night", spice: 8, minGroup: 2, maxGroup: 6, minTime: 90, maxTime: 180, cost: "$$", lateNight: true, venueQuery: ["bar"] },
  { id: "stargazing-park", title: "Park-Bench Stargaze", description: "Find a quiet bench in a park in {city} after dark. Stay 30 minutes. Count satellites.", category: "Late Night", spice: 3, minGroup: 2, maxGroup: 6, minTime: 30, maxTime: 60, cost: "free", lateNight: true, venueQuery: ["park"] },
  { id: "after-hours-photoshoot", title: "After-Hours Fashion Shoot", description: "Wear your most dramatic outfit at midnight in {city}. Photograph each other under streetlights for 30 minutes.", category: "Late Night", spice: 7, minGroup: 2, maxGroup: 6, minTime: 45, maxTime: 75, cost: "free", lateNight: true },
];
