export type QuestCategory =
  | "Chaos"
  | "Outdoor"
  | "Social"
  | "Creative"
  | "Food"
  | "Late Night";

export type QuestTemplate = {
  id: string;
  title: string;
  description: string;
  category: QuestCategory;
  spice: number; // 1-10
  minGroup: number;
  maxGroup: number;
  minTime: number; // minutes
  maxTime: number;
  lateNight?: boolean;
};

// {city} is substituted with the user's location at generation time.
export const QUESTS: QuestTemplate[] = [
  {
    id: "stranger-compliments",
    title: "Stranger Compliment Chain",
    description:
      "Each person must give a genuine compliment to 5 strangers in {city}. Bonus: get one to compliment you back.",
    category: "Social",
    spice: 4,
    minGroup: 2,
    maxGroup: 10,
    minTime: 30,
    maxTime: 90,
  },
  {
    id: "weirdest-cart",
    title: "Walmart 1am Weirdest-Cart Audit",
    description:
      "Hit a 24-hour store in {city}. Fill one shared cart with the weirdest items under $3 each. Pay together at checkout.",
    category: "Late Night",
    spice: 7,
    minGroup: 2,
    maxGroup: 6,
    minTime: 45,
    maxTime: 90,
    lateNight: true,
  },
  {
    id: "tech-meetup-chaos",
    title: "Tech Meetup Chaos Questions",
    description:
      "Crash a real startup/tech meetup in {city}. Each person must get a founder to seriously answer one absurd question.",
    category: "Social",
    spice: 5,
    minGroup: 2,
    maxGroup: 5,
    minTime: 60,
    maxTime: 150,
  },
  {
    id: "museum-sprint",
    title: "Museum 90-Min Photo Sprint",
    description:
      "No GPS. Enter and exit 4 museums or galleries in {city} within 90 minutes. Photograph the weirdest object in each.",
    category: "Creative",
    spice: 6,
    minGroup: 2,
    maxGroup: 6,
    minTime: 90,
    maxTime: 120,
  },
  {
    id: "bus-roulette",
    title: "Bus Roulette",
    description:
      "Board the next bus or train leaving {city}'s nearest stop. Ride 4 stops. Get off. Find food within 10 minutes.",
    category: "Chaos",
    spice: 6,
    minGroup: 1,
    maxGroup: 8,
    minTime: 60,
    maxTime: 180,
  },
  {
    id: "park-bench-philosophers",
    title: "Park Bench Philosophers",
    description:
      "Find a park in {city}. Sit on different benches. Strike up 3-minute philosophy conversations with anyone nearby.",
    category: "Outdoor",
    spice: 3,
    minGroup: 2,
    maxGroup: 6,
    minTime: 45,
    maxTime: 90,
  },
  {
    id: "fake-tourist",
    title: "Fake Tourist Mode",
    description:
      "Pretend you've never been to {city}. Ask locals for the 'best hidden spot.' Follow the top 3 recommendations.",
    category: "Social",
    spice: 4,
    minGroup: 2,
    maxGroup: 5,
    minTime: 90,
    maxTime: 180,
  },
  {
    id: "dollar-store-gifts",
    title: "Dollar Store Gift Exchange",
    description:
      "Everyone gets $5 at a dollar store in {city}. Buy gifts blindly for each other. Reveal at the nearest coffee shop.",
    category: "Creative",
    spice: 3,
    minGroup: 3,
    maxGroup: 8,
    minTime: 45,
    maxTime: 75,
  },
  {
    id: "karaoke-cold-open",
    title: "Karaoke Cold Open",
    description:
      "Find a karaoke spot in {city}. First person up sings a song chosen entirely by the group. No vetoes.",
    category: "Late Night",
    spice: 6,
    minGroup: 2,
    maxGroup: 8,
    minTime: 60,
    maxTime: 180,
    lateNight: true,
  },
  {
    id: "skyline-hunt",
    title: "Skyline Hunt",
    description:
      "Find the highest publicly accessible vantage point in {city}. Take a group photo at the top. Free or paid.",
    category: "Outdoor",
    spice: 4,
    minGroup: 1,
    maxGroup: 8,
    minTime: 60,
    maxTime: 120,
  },
  {
    id: "open-mic-dare",
    title: "Open Mic Dare",
    description:
      "Find an open mic in {city} tonight. One member of the group must perform. Audience picks the topic on the spot.",
    category: "Chaos",
    spice: 9,
    minGroup: 2,
    maxGroup: 6,
    minTime: 90,
    maxTime: 180,
    lateNight: true,
  },
  {
    id: "thrift-outfit",
    title: "Thrift Outfit Swap",
    description:
      "$10 each at a thrift store in {city}. Pick out an entire outfit for the person on your left. Must wear it all day.",
    category: "Creative",
    spice: 5,
    minGroup: 3,
    maxGroup: 8,
    minTime: 75,
    maxTime: 120,
  },
  {
    id: "ice-cream-crawl",
    title: "Ice Cream Crawl",
    description:
      "Hit 3 different ice cream/dessert spots in {city}. One scoop each, rate on a chaotic 1-10 scale.",
    category: "Food",
    spice: 2,
    minGroup: 2,
    maxGroup: 10,
    minTime: 60,
    maxTime: 120,
  },
  {
    id: "spice-gauntlet",
    title: "Spice Gauntlet",
    description:
      "Find the spiciest dish on any menu in {city}. Order one. Everyone takes one bite. No drinks for 60 seconds.",
    category: "Food",
    spice: 8,
    minGroup: 2,
    maxGroup: 8,
    minTime: 45,
    maxTime: 90,
  },
  {
    id: "diner-deep-talk",
    title: "Diner Deep Talk",
    description:
      "Find a 24-hour diner in {city}. Order fries. Each person answers one question they've never answered honestly.",
    category: "Late Night",
    spice: 5,
    minGroup: 2,
    maxGroup: 6,
    minTime: 60,
    maxTime: 120,
    lateNight: true,
  },
  {
    id: "playground-takeover",
    title: "Playground Takeover (Legal)",
    description:
      "Find a public playground in {city}. Hold a 10-minute swing competition. Loser buys snacks.",
    category: "Outdoor",
    spice: 3,
    minGroup: 2,
    maxGroup: 6,
    minTime: 30,
    maxTime: 60,
  },
  {
    id: "mystery-menu",
    title: "Mystery Menu",
    description:
      "Each person orders for the person across from them at a restaurant in {city}. No allergies, no swaps.",
    category: "Food",
    spice: 6,
    minGroup: 2,
    maxGroup: 8,
    minTime: 60,
    maxTime: 120,
  },
  {
    id: "subway-portrait",
    title: "Public Transit Portrait Session",
    description:
      "On {city}'s transit, sketch the person sitting across from you (with consent). Trade sketches at the end.",
    category: "Creative",
    spice: 6,
    minGroup: 2,
    maxGroup: 6,
    minTime: 45,
    maxTime: 90,
  },
  {
    id: "bookstore-blind-date",
    title: "Bookstore Blind Date",
    description:
      "At a bookstore in {city}, each person picks a book for someone else based on vibes alone. Read aloud one page.",
    category: "Creative",
    spice: 2,
    minGroup: 2,
    maxGroup: 6,
    minTime: 45,
    maxTime: 90,
  },
  {
    id: "scavenger-five",
    title: "Five-Thing Scavenger",
    description:
      "In 60 minutes around {city}: find a feather, something purple, a free sticker, a stranger's recommendation, and a coin.",
    category: "Outdoor",
    spice: 3,
    minGroup: 2,
    maxGroup: 8,
    minTime: 60,
    maxTime: 75,
  },
  {
    id: "elevator-pitch",
    title: "Elevator Pitch Roulette",
    description:
      "Find a tall building lobby in {city}. Each person rides up with a stranger and pitches them a fake startup idea.",
    category: "Chaos",
    spice: 7,
    minGroup: 2,
    maxGroup: 5,
    minTime: 45,
    maxTime: 90,
  },
  {
    id: "dance-floor-import",
    title: "Dance Floor Import",
    description:
      "Find a place in {city} with music. Start a 30-second dance routine. See how many strangers join in.",
    category: "Chaos",
    spice: 7,
    minGroup: 3,
    maxGroup: 8,
    minTime: 30,
    maxTime: 90,
    lateNight: true,
  },
  {
    id: "free-museum-day",
    title: "Free Museum Speedrun",
    description:
      "Find any free museum or gallery in {city}. Speedrun it in 20 minutes. Each person picks their favorite piece.",
    category: "Creative",
    spice: 2,
    minGroup: 1,
    maxGroup: 8,
    minTime: 30,
    maxTime: 60,
  },
  {
    id: "stranger-pic",
    title: "Stranger of the Day",
    description:
      "Approach one stranger in {city}. Ask their life story. Buy them a coffee. Post nothing.",
    category: "Social",
    spice: 5,
    minGroup: 1,
    maxGroup: 4,
    minTime: 30,
    maxTime: 60,
  },
  {
    id: "midnight-snack-quest",
    title: "Midnight Snack Quest",
    description:
      "After midnight in {city}, find the strangest open food spot. Order whatever the cashier recommends.",
    category: "Late Night",
    spice: 6,
    minGroup: 2,
    maxGroup: 6,
    minTime: 45,
    maxTime: 90,
    lateNight: true,
  },
  {
    id: "rooftop-recon",
    title: "Rooftop Recon",
    description:
      "Find a (legal) rooftop bar or terrace in {city}. Order the most colorful drink on the menu. Toast loudly.",
    category: "Social",
    spice: 4,
    minGroup: 2,
    maxGroup: 8,
    minTime: 60,
    maxTime: 120,
  },
  {
    id: "graffiti-tour",
    title: "Graffiti Self-Tour",
    description:
      "Walk a single mile in {city} photographing every piece of street art. Vote on the best at the end.",
    category: "Outdoor",
    spice: 2,
    minGroup: 1,
    maxGroup: 6,
    minTime: 45,
    maxTime: 90,
  },
  {
    id: "uber-roulette",
    title: "Rideshare Roulette",
    description:
      "Open a rideshare in {city}. Pick the third suggestion. Go there. Find dinner within 15 minutes of arrival.",
    category: "Chaos",
    spice: 6,
    minGroup: 2,
    maxGroup: 4,
    minTime: 90,
    maxTime: 180,
  },
  {
    id: "story-strangers",
    title: "Three Stories, Three Strangers",
    description:
      "Each person collects a 60-second story from a stranger in {city}. Retell them all at a bar later.",
    category: "Social",
    spice: 5,
    minGroup: 2,
    maxGroup: 6,
    minTime: 75,
    maxTime: 150,
  },
  {
    id: "vintage-photo",
    title: "Vintage Photo Recreation",
    description:
      "Find an old postcard of {city}. Recreate the photo with the group at the exact location.",
    category: "Creative",
    spice: 3,
    minGroup: 2,
    maxGroup: 8,
    minTime: 60,
    maxTime: 120,
  },
  {
    id: "improv-tour",
    title: "Improv Walking Tour",
    description:
      "One person leads a totally made-up historical tour of {city}. Every fact is a lie. Audience must keep a straight face.",
    category: "Creative",
    spice: 5,
    minGroup: 3,
    maxGroup: 8,
    minTime: 45,
    maxTime: 90,
  },
  {
    id: "wildcard-bartender",
    title: "Wildcard Bartender",
    description:
      "At a bar in {city}, tell the bartender three adjectives. Drink whatever they make. No refusals.",
    category: "Late Night",
    spice: 7,
    minGroup: 2,
    maxGroup: 6,
    minTime: 45,
    maxTime: 90,
    lateNight: true,
  },
  {
    id: "park-picnic-blind",
    title: "Blind Picnic",
    description:
      "Each person brings one mystery snack to a park in {city}. Picnic-style, blind taste-test, rank them.",
    category: "Food",
    spice: 3,
    minGroup: 3,
    maxGroup: 8,
    minTime: 45,
    maxTime: 90,
  },
  {
    id: "alphabet-walk",
    title: "Alphabet Walk",
    description:
      "Walk through {city} and photograph 26 things, one for each letter, in order. Time limit: 90 minutes.",
    category: "Outdoor",
    spice: 4,
    minGroup: 1,
    maxGroup: 6,
    minTime: 90,
    maxTime: 120,
  },
  {
    id: "stranger-dance",
    title: "Stranger Slow Dance",
    description:
      "At a bar or venue in {city} with music, politely ask one stranger for a 30-second dance. Group cheers them on.",
    category: "Chaos",
    spice: 9,
    minGroup: 3,
    maxGroup: 6,
    minTime: 60,
    maxTime: 120,
    lateNight: true,
  },
  {
    id: "best-pastry",
    title: "Best Pastry in {city}",
    description:
      "Visit 3 bakeries in {city}. One pastry each. Determine the winner by group vote and crown them with a paper crown.",
    category: "Food",
    spice: 2,
    minGroup: 2,
    maxGroup: 6,
    minTime: 90,
    maxTime: 150,
  },
  {
    id: "trash-treasure",
    title: "Trash to Treasure",
    description:
      "Find one piece of street trash in {city}. Turn it into art on the spot. Photograph and leave it for someone else.",
    category: "Creative",
    spice: 3,
    minGroup: 2,
    maxGroup: 6,
    minTime: 30,
    maxTime: 60,
  },
  {
    id: "playground-tag",
    title: "Adult Tag",
    description:
      "Find a green space in {city}. Play one full round of tag. Wear whatever you're already wearing. No quitting.",
    category: "Outdoor",
    spice: 5,
    minGroup: 4,
    maxGroup: 10,
    minTime: 30,
    maxTime: 60,
  },
  {
    id: "menu-translator",
    title: "Menu Translator",
    description:
      "Pick a restaurant in {city} with a menu in another language. No phones, order by pointing only.",
    category: "Food",
    spice: 5,
    minGroup: 2,
    maxGroup: 6,
    minTime: 60,
    maxTime: 90,
  },
  {
    id: "two-truths-locals",
    title: "Two Truths and a Local",
    description:
      "Each person collects one weird local fact from a stranger in {city}. Play two truths and a lie with them later.",
    category: "Social",
    spice: 4,
    minGroup: 3,
    maxGroup: 6,
    minTime: 60,
    maxTime: 120,
  },
  {
    id: "skate-or-roll",
    title: "Skate or Roll",
    description:
      "Rent skates, scooters, or bikes in {city}. Pick a destination 2 miles away. Race there. Loser gets coffee for the group.",
    category: "Outdoor",
    spice: 5,
    minGroup: 2,
    maxGroup: 6,
    minTime: 60,
    maxTime: 120,
  },
  {
    id: "stranger-selfie",
    title: "Stranger Selfie Roulette",
    description:
      "Politely ask 5 strangers in {city} for a group selfie. Collect them. Build a stranger photo album.",
    category: "Social",
    spice: 4,
    minGroup: 2,
    maxGroup: 8,
    minTime: 45,
    maxTime: 90,
  },
  {
    id: "candy-store-blind",
    title: "Candy Store Blindfold",
    description:
      "At a candy store in {city}, one person is blindfolded and picks $5 of candy by feel. Group eats it all.",
    category: "Food",
    spice: 4,
    minGroup: 2,
    maxGroup: 6,
    minTime: 30,
    maxTime: 60,
  },
  {
    id: "vinyl-hunt",
    title: "Vinyl Hunt",
    description:
      "Find a record store in {city}. Each person buys the album with the weirdest cover. Listen to a track each at home.",
    category: "Creative",
    spice: 3,
    minGroup: 2,
    maxGroup: 6,
    minTime: 60,
    maxTime: 90,
  },
  {
    id: "haunt-walk",
    title: "Self-Guided Haunt Walk",
    description:
      "After dark, walk through the oldest neighborhood in {city}. Each person invents a ghost story for one building.",
    category: "Late Night",
    spice: 4,
    minGroup: 2,
    maxGroup: 8,
    minTime: 60,
    maxTime: 120,
    lateNight: true,
  },
  {
    id: "movie-poster",
    title: "Movie Poster Group Pose",
    description:
      "Pick a famous movie poster. Recreate it in 3 different iconic spots around {city}. Best pose wins.",
    category: "Creative",
    spice: 4,
    minGroup: 3,
    maxGroup: 8,
    minTime: 60,
    maxTime: 120,
  },
  {
    id: "fortune-cookie-mission",
    title: "Fortune Cookie Mission",
    description:
      "Find a fortune cookie in {city}. Whatever it says, the group must do it (within reason) within the hour.",
    category: "Chaos",
    spice: 7,
    minGroup: 2,
    maxGroup: 6,
    minTime: 60,
    maxTime: 120,
  },
  {
    id: "best-bench",
    title: "Best Bench in {city}",
    description:
      "Find and rate 5 benches in {city} by view, comfort, and vibes. Award a sticky note to the winning bench.",
    category: "Outdoor",
    spice: 1,
    minGroup: 1,
    maxGroup: 6,
    minTime: 60,
    maxTime: 120,
  },
  {
    id: "yes-day-mini",
    title: "Mini Yes-Day",
    description:
      "For the next 90 minutes in {city}, say yes to any reasonable suggestion from any group member.",
    category: "Chaos",
    spice: 8,
    minGroup: 2,
    maxGroup: 6,
    minTime: 90,
    maxTime: 180,
  },
  {
    id: "language-exchange",
    title: "Language Exchange Mission",
    description:
      "Find one stranger in {city} who speaks a language none of you do. Learn 3 words. Use them in your next order.",
    category: "Social",
    spice: 4,
    minGroup: 2,
    maxGroup: 5,
    minTime: 45,
    maxTime: 90,
  },
  {
    id: "secret-handshake",
    title: "Secret Handshake Genesis",
    description:
      "Invent a 6-step group handshake in {city}. Perform it at 3 different public spots. Get a stranger to learn it.",
    category: "Creative",
    spice: 4,
    minGroup: 3,
    maxGroup: 6,
    minTime: 45,
    maxTime: 90,
  },
  {
    id: "free-event-find",
    title: "Free Event Crash",
    description:
      "Find any free event happening in {city} tonight. Show up. Stay at least 30 minutes. Make one new friend.",
    category: "Social",
    spice: 5,
    minGroup: 1,
    maxGroup: 6,
    minTime: 90,
    maxTime: 180,
  },
];
